### ISSUE TITLE
Expired submissions are displayed as Registred

### ISSUE THREAD

**Issue by clesaege** [Proof-Of-Humanity/proof-of-humanity-web#10]
![image](https://user-images.githubusercontent.com/8873352/107663737-9cac8680-6c83-11eb-9452-0bfce9458acc.png)

**Comment by epiqueras** [comment]
@pliniobraga we need a design for the new "expired" state.

**Comment by epiqueras** [comment]
<img width="220" alt="Screen Shot 2021-02-11 at 2 47 42 PM" src="https://user-images.githubusercontent.com/19157096/107708288-19396800-6c78-11eb-8ab0-d7fa8d898d9c.png">

I added this for now.

**Comment by pliniobraga** [comment]
Included the expired state on the design @epiqueras : 
![Screen Shot 2021-02-15 at 19 10 10](https://user-images.githubusercontent.com/15757255/107997576-d5b96380-6fc1-11eb-8271-7cca7e5739c8.png)
