### ISSUE TITLE
Do not show "start accruing" when it shouldn't.

### ISSUE THREAD

**Issue by clesaege** [Proof-Of-Humanity/proof-of-humanity-web#101]
It shows a "start accruing" button on other people registered profiles
![image](https://user-images.githubusercontent.com/8873352/110980726-13f63880-835e-11eb-93ed-d8bd2c8402e6.png)

**Comment by mtsalenc** [comment]
Implemented in https://github.com/Proof-Of-Humanity/proof-of-humanity-web/commit/21f0ad718d8ca739df42740cd79908fdd0073443
