### ISSUE TITLE
Fix "Accepted" and "Renewal" for people who withdrew their submissions

### ISSUE THREAD

**Issue by clesaege** [Proof-Of-Humanity/proof-of-humanity-web#112]
![image](https://user-images.githubusercontent.com/8873352/111053223-d4ad1200-8459-11eb-9d7b-57cd96160486.png)
It's currently showing 51 years ago which is probably due to their time of acceptance not being set.
We should not show those if the time data is 0.

**Comment by mtsalenc** [comment]
This bug is not present anymore.
