### ISSUE TITLE
Video playback

### ISSUE THREAD

**Issue by btcethph** [Proof-Of-Humanity/proof-of-humanity-web#113]
https://user-images.githubusercontent.com/63893001/111060068-47a79e80-84d5-11eb-9c27-f008ea8e3974.mp4

The video often doesn't play right and shows flashing green or just green screen instead

**Comment by jragosa** [comment]
Link: [https://app.proofofhumanity.id/profile/0xd2a08007eeeaf1f81eef54ba6a8c4effa1e545c6?network=mainnet](https://app.proofofhumanity.id/profile/0xd2a08007eeeaf1f81eef54ba6a8c4effa1e545c6?network=mainnet)

Video works for me. Can you provide info about your browser and OS?

**Comment by btcethph** [comment]
Brave/Chrome in windows. It happens at random

**Comment by ferittuncer** [comment]
Takes a bit to load but plays just fine. Can't reproduce.
