### ISSUE TITLE
Add a "Wihdraw Submission" button for profiles in vouching phase

### ISSUE THREAD

**Issue by jragosa** [Proof-Of-Humanity/proof-of-humanity-web#117]
withdrawSubmission() fucntion does not have a button in the UI.

![image](https://user-images.githubusercontent.com/34345327/111073637-c1448a00-84df-11eb-9462-8a66da292d89.png)

Let's add a button on the bottom left in vouching phase profiles (where "Challenge Registration" button is for Pending registration profiles).
![image](https://user-images.githubusercontent.com/34345327/111073691-e933ed80-84df-11eb-8e3e-98ffcf9464be.png)

**Comment by hbarcelos** [comment]
Done.
