### ISSUE TITLE
Vouching keeps loading on other users when you have a vouching TX pending.

### ISSUE THREAD

**Issue by clesaege** [Proof-Of-Humanity/proof-of-humanity-web#120]
I'm vouching for everyone I know and if my previous vouching TX is not mined, I see the button loading when I try to vouch for someone else.
![image](https://user-images.githubusercontent.com/8873352/111079587-8730b380-84f2-11eb-8791-8582d437dd07.png)

**Comment by clesaege** [comment]
I accelerated the previous TX which is mined and it keeps loading preventing me from vouching other people.

**Comment by clesaege** [comment]
Quick fix would be to never show this loading symbol blocking the button. We can then show this loading symbol at the individual level.

**Comment by mtsalenc** [comment]
Displaying the loading indicator (i.e. tracking the tx status per-profile) is not trivial with the current project structure. Instead, I'm just removing the loading indicator to prevent vouching other people.
