### ISSUE TITLE
Fix picture not being displayed (if it was not submitted show a warning)

### ISSUE THREAD

**Issue by clesaege** [Proof-Of-Humanity/proof-of-humanity-web#122]
https://app.proofofhumanity.id/profile/0x0d411733722abd798579e5478503414bfc467907?network=mainnet

**Comment by hbarcelos** [comment]
The main issue here is that the image **was** uploaded, but the file is corrupted.
There's no easy way of checking if a JPEG or PNG file is corrupted in the browser, unless we go as deep as reading the image blob and validating ourselves.

Not sure if it's worth fixing right now.

**Comment by mtsalenc** [comment]
Closing this as it is unfeasible to fix.
