### ISSUE TITLE
Renewal period for seeders is off

### ISSUE THREAD

**Issue by clesaege** [Proof-Of-Humanity/proof-of-humanity-web#123]
![image](https://user-images.githubusercontent.com/8873352/111088657-27e99800-8520-11eb-9c7c-bf1ba666348e.png)
https://app.proofofhumanity.id/profile/0x188637F91948E5d40587FDB0bcd8FFDC7aFA0887?network=mainnet

**Comment by mtsalenc** [comment]
I don't think there is anything wrong with the UI, its just that it was confusing.
To improve it I changed the label:
![Screenshot from 2021-03-15 14-25-48](https://user-images.githubusercontent.com/9872474/111195166-be5a9f80-859a-11eb-9b83-1817c7001c7c.png)
