### ISSUE TITLE
Tweet Button for Viral Growth Hacking

### ISSUE THREAD

**Issue by LorensHuculak** [Proof-Of-Humanity/proof-of-humanity-web#126]
**Describe the solution you'd like.**
To increase the growth rate of PoH, we could add a "Tweet" button that sends out something like: I just joined Proof of Humanity to receive monthly Universal Basic Income. I can now vouch for new applicants. Check out my profile!

This would greatly increase the virality of the onboarding and people would also comment on these tweets for vouches.

**Describe alternatives you've considered.**
Alternatively, we could add this button to our "YOU ARE REGISTERED!" mail (after being vouched + registrated), asking the applicants kindly to send it out.

**Comment by defi-er** [comment]
Good idea

**Comment by jragosa** [comment]
@LorensHuculak There is already a tweet button on profiles that is quite used. Do you want to change that?

**Comment by jragosa** [comment]
There is a tweet button.
