### ISSUE TITLE
No "Removal Request" button in "Registered" profile when there should be one

### ISSUE THREAD

**Issue by jragosa** [Proof-Of-Humanity/proof-of-humanity-web#127]
"Registered" profiles should have the button "Removal Request" to submit a request for removal of the profile but it is not displayed

**Comment by unknownunknown1** [comment]
The reason might be that renewal period duration is set equal to submission duration making it impossible to make a removal request because it's being timed out by default. Even if it's not the main cause we should change the value of renewal period anyway

**Comment by jragosa** [comment]
Fixed
