### ISSUE TITLE
Add a button "Withdraw submission" for profiles in "Vouching Phase"

### ISSUE THREAD

**Issue by jragosa** [Proof-Of-Humanity/proof-of-humanity-web#128]
Currently, people have to call the withdrawSubmission directly from etherscan if they want to get their deposit back when they made a mistake in their profile, this should be in the UI.

A "Withdraw submission" button should be displayed for profiles in Vouching phase at the bottom left of the profile (same location than "Challenge Request" button for "Pending registration" profiles)

**Comment by unknownunknown1** [comment]
Implementing this function directly in the UI might also solve the issue with reverting when registering again the recently withdrawn address
