### ISSUE TITLE
File upload in Evidence does not work

### ISSUE THREAD

**Issue by jragosa** [Proof-Of-Humanity/proof-of-humanity-web#129]
Impossible to upload files in "Submit Evidence" Modal

![image](https://user-images.githubusercontent.com/34345327/111278901-65424880-863a-11eb-9cc3-c6aff57114fb.png)

**Comment by arielsbecker** [comment]
Hi! I can verify that the error is real. Tried earlier [here](https://app.proofofhumanity.id/profile/0xC12Df5F402A8B8BEaea49ed9baD9c95fCcbfE907?network=mainnet) without any luck both times.

In my second attempt I opened the dev console to force show the file input, so as to discard it wasn't picking my file correctly. It does. However, once I send the request to the server, I don't receive any error, but the files are missing nonetheless.

Attaching a screencap just in case it is of any help. I tried uploading that ZIP without any luck. My first attempt was a 2 MB JPG.

![0080](https://user-images.githubusercontent.com/9767478/111846990-b5453780-88e6-11eb-9791-52d92aebd0e1.png)
