### ISSUE TITLE
Typing 0. reset the field

### ISSUE THREAD

**Issue by clesaege** [Proof-Of-Humanity/proof-of-humanity-web#13]
![image](https://user-images.githubusercontent.com/8873352/107666242-35dc9c80-6c86-11eb-8956-179467049969.png)

If you type "0." (like as a start of "0.13"), the field value resets which prevents from typing "0.13".

**Comment by epiqueras** [comment]
I was able to reproduce and fix this.

It was due to different browsers having various heuristics for calling the change handlers when a period is inserted. Interestingly, some do it, and some don't.
