### ISSUE TITLE
search box doesn't work in some cases

### ISSUE THREAD

**Issue by lalbinati** [Proof-Of-Humanity/proof-of-humanity-web#131]
The search box of the registry does not bring results for partial matches or eth address.

e.g. given the user Leo Fer profile 
https://app.proofofhumanity.id/profile/0xb30851b276e19fbbcbf3d82825a8cab68823ddfa?network=mainnet

when I type in the search box the word "le" it doesn't bring any result. On the other hand, if I type Leo, which is an exact word contained in the profile name, it does bring the profile included in the results, together with other users which have the exact word Leo in the profile name.
Full name " Leonardo Ferlini" is not matched at all in the search, not even typing the exact full name.
Search by ethereum address also doesn't bring any results.

It  should bring results for partial matches or for any text contained in the profile

Windows 10, chrome Version 89.0.4389.82 (Official Build) (64-bit)

**Comment by lalbinati** [comment]
Hi, I see an improvement has been pushed for partial matches but search is still case sensitive and is still not returning results for the remaining information of the profile. e.g. last name

**Comment by mtsalenc** [comment]
Please follow https://github.com/Proof-Of-Humanity/proof-of-humanity-web/issues/192
