### ISSUE TITLE
Allow automatically removed from the UI a “self-remove” request

### ISSUE THREAD

**Issue by Ayelaurencena** [Proof-Of-Humanity/proof-of-humanity-web#135]
Users for multiple reasons may need to be deleted from the platform right away to avoid physical harm (ie. domestic violence) and/or financial risks ( ie. use of the incorrect wallet). 

For user IRL security reasons it would be important to implement a way to allow self-removals to execute almost immediately. 

_Possible ideas:_

- Request a second confirmation (to reduce the chance of a security vulnerability) like the need to receive a vouch
- Implement a Social Recovery feature, instead of Recovery would work for Confirmation of this transaction request (Removal) and others that could be added in the future and can be benefited from it.
- ..

.

**Comment by jragosa** [comment]
The current version of the smart contract does not allow for instant removal of a profile outside of "Vouching Phase". All removal methods have a 3.5 days delay.

We can explore solutions such as hiding profiles in the frontend when a challenge or removal request has been done by the same address as the submitter. Though this does not erase the submission from an expert looking at the blockchain as it is immutable.

**Comment by clesaege** [comment]
The smart contract cannot remove people and even if removed the data would still be on chain.

**Comment by Ayelaurencena** [comment]
Hiding the profile from the FE would do much the work
