### ISSUE TITLE
Total number of profiles displayed on the top right should not count "Removed" and "Expired" profiles and should adapt to the filter selected

### ISSUE THREAD

**Issue by jragosa** [Proof-Of-Humanity/proof-of-humanity-web#138]
The current total number of profiles displayed on the top right seems to count "Removed" and "Expired" profiles.

I think it should not.

![image](https://user-images.githubusercontent.com/34345327/111504595-1f73a600-8748-11eb-884f-fafbaaf6e6ab.png)

+ It should display the number of profiles with the status selected by the filter.

**Comment by alcercu** [comment]
Hello!
"Removed" and "Expired" profiles are counted on the "All" page since those profiles also appear on this page. But, **now** you can change the filter and the number displayed will correctly reflect how many profiles are on the determined category 🙌🏻 
Thanks!
