### ISSUE TITLE
"Fund Submission" Tx reverts when trying to fund from the submitter address (with crowdfunded profile)

### ISSUE THREAD

**Issue by jragosa** [Proof-Of-Humanity/proof-of-humanity-web#139]
2 different people reported this bug:

They submitted their profile with the "Crowdfund" option and 0 deposit.
 
Later, they tried to fund their own submission with the same address and the Tx was reverted (max gas limit).

Did not try to reproduce it on Kovan PoH yet.

**Comment by ferittuncer** [comment]
Can't reproduce.
