### ISSUE TITLE
Show instructions for the face picture

### ISSUE THREAD

**Issue by clesaege** [Proof-Of-Humanity/proof-of-humanity-web#14]
![image](https://user-images.githubusercontent.com/8873352/107666890-ef3b7200-6c86-11eb-9129-f3b96ee5e4ad.png)

Show instructions for the face picture (Picture Instructions).
Show instructions about the face on the video section.
Show a link to the primary document.

**Comment by epiqueras** [comment]
Done

Note that the primary document will link to nowhere until the meta evidence is updated with one.
