### ISSUE TITLE
Vide recorded through webcam is recorded in .mkv and is not accepted

### ISSUE THREAD

**Issue by jragosa** [Proof-Of-Humanity/proof-of-humanity-web#143]
Another user and myself noticed that videos recorded through the webcam are in .mkv and thus, not accepted.

![image](https://user-images.githubusercontent.com/34345327/111619138-7b403c80-87e5-11eb-9898-254a679aa3c1.png)

**Comment by hbarcelos** [comment]
@jragosa this could be related to another bug I just fixed. Could you please ask the user to try again?

**Comment by mtsalenc** [comment]
Recording directly from the webcam has been removed due to some users facing issues with audio issues.
