### ISSUE TITLE
The accrued UBI displays the wrong balance

### ISSUE THREAD

**Issue by santisiri** [Proof-Of-Humanity/proof-of-humanity-web#147]
**Describe the Bug**

The interface shows the UBI probably from `accruedSince` in the contract but that's not necessarily the `balanceOf` the account. It should display (as it does on wallets) the value obtained from `balanceOf` that account.

**To Reproduce**

Compare UBI from an accruing account on Metamask and the value on the UI from the same account.

**Expected Behavior**

Both, wallet and UI should display the same value. The one from `balanceOf`.

**Screenshots**

<img width="414" alt="Screen Shot 2021-03-18 at 6 09 53 PM" src="https://user-images.githubusercontent.com/2153166/111667742-4ea41900-8815-11eb-88ed-854293db1b80.png">

**Device and Browser Information**

Mac & Chrome

**Comment by jragosa** [comment]
@santisiri I think it is still useful to display the total value accrued by a profile since starting accrual.
Either we don't touch it at all, or add a "Current Balance" display.

**Comment by santisiri** [comment]
yeah.. maybe because I found it a bit confusing, we could display both. But I fear that might even make it more confusing. 

okay, let's make this about accrued ubi only. 👍

**Comment by ferittuncer** [comment]
So, closing then?
