### ISSUE TITLE
Maximum gas limit (Tx reverting) when trying to challenge registration

### ISSUE THREAD

**Issue by jragosa** [Proof-Of-Humanity/proof-of-humanity-web#150]
I am getting a maximum gas limit (Tx reverting) when trying to challenge a pending registration:
![image](https://user-images.githubusercontent.com/34345327/111754100-e3e7f180-8897-11eb-8ec8-33456d955594.png)
![image](https://user-images.githubusercontent.com/34345327/111754112-e64a4b80-8897-11eb-8c73-ba536dab676e.png)

This was not happening before as I challenged a registration with no issues 2 days ago.

**Comment by ferittuncer** [comment]
Is this available?

**Comment by jragosa** [comment]
Non-reproducible currenlty.
