### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by coluccini** [Proof-Of-Humanity/proof-of-humanity-web#151]
I think that if we want PoH becomes global, we should have the platform translated to different languages.

Does someone knows if this is already on the roadmap? if not, I can take the task of preparing the web to handle different languages and, if I still have some time, translate it to Spanish.

**Comment by lalbinati** [comment]
I suggest using linguo for the required translations

**Comment by mtsalenc** [comment]
Unfortunately this likely won't be implement in the short or medium term because verifying submissions means running the submission against machine learning algorithms to detect duplicates. This includes verifying the audio of the video.
