### ISSUE TITLE
Adding a help section to redirect users to tutorial, FAQ, TG channels

### ISSUE THREAD

**Issue by jragosa** [Proof-Of-Humanity/proof-of-humanity-web#152]
Users right now are not finding the help needed to use the app as there is no link to tutorials or FAQ on the app frontend.

**Implementation:**

![image](https://user-images.githubusercontent.com/34345327/111756588-ab95e280-889a-11eb-8079-5e858170a413.png)

- Get Help: https://t.me/proofhumanity
- Report a Bug: https://github.com/Proof-Of-Humanity/proof-of-humanity-web/issues
- Tutorial: https://kleros.gitbook.io/docs/products/proof-of-humanity/proof-of-humanity-tutorial
- FAQ: https://kleros.gitbook.io/docs/products/proof-of-humanity/poh-faq

Icons are on PoH Figma (ask the link to Plinio if you don't have it)

**Comment by hbarcelos** [comment]
FIxed by [cb8d62](https://github.com/Proof-Of-Humanity/proof-of-humanity-web/commit/cb8d621ecbc6175f11412e4d892aabca1be2657b).
