### ISSUE TITLE
Case 560

### ISSUE THREAD

**Issue by ferittuncer** [Proof-Of-Humanity/proof-of-humanity-web#157]
Something wrong with this profile: https://proof-of-humanity.netlify.app/profile/0x8d93471dfd2a9d9bdc56edee93f3fc57b8078d68?network=mainnet
![Screenshot from 2021-03-24 17-15-19](https://user-images.githubusercontent.com/3106907/112325196-881cce80-8cc4-11eb-83da-950b921f33de.png)

Also, it is challenged and disputes do not get displayed properly.

![Screenshot from 2021-03-24 17-19-05](https://user-images.githubusercontent.com/3106907/112325820-0f6a4200-8cc5-11eb-90e4-c343edb41be5.png)
![Screenshot from 2021-03-24 17-16-49](https://user-images.githubusercontent.com/3106907/112325832-11cc9c00-8cc5-11eb-9a65-ef16343780fb.png)

None of Poh, Court, and Dispute Resolver can display it properly. It seems like a missing piece of metaevidence. Needs to be investigated.

**Comment by mtsalenc** [comment]
This profile was submitted before the launch was announced, when there was a buggy meta evidence file. https://github.com/Proof-Of-Humanity/proof-of-humanity-web/pull/162 works around it so the profile can be viewed.
