### ISSUE TITLE
Registration form is not submitted

### ISSUE THREAD

**Issue by faocampo** [Proof-Of-Humanity/proof-of-humanity-web#159]
**Describe the Bug**
After several attempts, I haven't been able to submit the registration info since the page gets in a "loading" stage for ever.

**To Reproduce**
1. fill all fields out (I've tried recording picture and video using both the browser with webcam and locally with video capturing software)
2. Confirm the post

**Expected Behavior**
Some feedback message confirming the submission

**Obtained Behavior**
What I got the first time was a submit button with the _loading_ image and no other response. Now I'm not even able to confirm the submission but I'm getting a network error

**Screenshots**
![poh form](https://user-images.githubusercontent.com/81325633/112369926-88fd3280-8cbb-11eb-9732-394c5c3badca.png)

<img width="1636" alt="Screen Shot 2021-03-24 at 16 07 33" src="https://user-images.githubusercontent.com/81325633/112369725-476c8780-8cbb-11eb-91c9-6ba27d885cd2.png">

**Device and Browser Information**
Mac OS (Macbook Pro) Firefox 86.0.1

ERROR Transcript
```
Security Error: Content at https://app.proofofhumanity.id/profile/0x15715b4D3B2E494343dDDB266a9cd39Bcb79826C?network=mainnet may not load data from blob:https://app.proofofhumanity.id/47b696e0-38d6-b149-ad3b-a46357424828.

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ipfs.kleros.io/add. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

Warning: An unhandled error was caught from submitForm() TypeError: NetworkError when attempting to fetch resource. 25c95608911bd1bb7bde93e383e165381695162a.368510917994eb0f1a54.js:1:1334276
```

**Comment by CCern** [comment]
I am having the same issue...
After several attempts, I haven't been able to submit the registration info since the page gets in a "loading" stage for ever.
I tried desktop and web mobile versions... Same thing.
Pic/video size, ETH balance, etc: all seem fine. But still cant get pass the Submit button...
@faocampo were you able to solve this?

**Comment by faocampo** [comment]
Hi CCErn!

You know it was totally my fault for being a newbie in the Ethereum network
and DApps world.... and a lack of usability features in the system too:

Basically what is happening is that as soon one clicks on the "submit" -if
you've chosen to transfer the required ETH amount- is that the Wallet asks
you to confirm the transaction. Since of course the wallet is in my mobile
phone, I wasn't looking at it and never realized that such confirmation was
pending. Same thing for when you register your email for receiving
notifications.

I hope this is your case and this solves the problem.

Best!



Federico A. Ocampo
