### ISSUE TITLE
Display an information message after submitting when in "my profile" after you submitted

### ISSUE THREAD

**Issue by clesaege** [Proof-Of-Humanity/proof-of-humanity-web#17]
![image](https://user-images.githubusercontent.com/8873352/107669660-e0a28a00-6c89-11eb-891a-ebcee9b7bd2e.png)
What I see in "My profile" shortly after making a submission. I see my profile after a few minutes. We need to explain "Your submission is being processed" and auto refresh once it is.

**Comment by epiqueras** [comment]
I have a good idea for this.

**Comment by epiqueras** [comment]
This was tough, but I came up with a nice hook that lets us keep spinners going until the graph syncs and then refetch the whole page as soon as it's done.

**Comment by epiqueras** [comment]
https://user-images.githubusercontent.com/19157096/107743103-2466b500-6cc5-11eb-92a1-b0cb003f7dd7.mov


https://user-images.githubusercontent.com/19157096/107743140-35172b00-6cc5-11eb-93ab-d97408187b5c.mov
