### ISSUE TITLE
Registration Form keeps loading

### ISSUE THREAD

**Issue by MatayoshiMariano** [Proof-Of-Humanity/proof-of-humanity-web#171]
**Describe the Bug**
After linking my cypto.com wallet with WalletConnect to the proofofhumanity app i fill out my profile an click Submit. The submit button keeps on loading and nothing happen

Am i missing something?

**Screenshots**
![Screenshot from 2021-03-30 12-16-46](https://user-images.githubusercontent.com/4236217/113013179-dcef9780-9151-11eb-8f31-e67c52da1001.png)

**Comment by MatayoshiMariano** [comment]
@mtsalenc now the only available wallet is `autherum` which is disabled for new users, how hard is to fix `WalletConnect` integration?

**Comment by mtsalenc** [comment]
[It doesn't look like its an issue on our side](https://github.com/Web3Modal/web3modal/issues/202), but on a library we use. We are still trying to get it to work. Will have an answer by tomorrow.

In the meantime, the other option is to use metamask (which will only show if you have the extension)

**Comment by lucasgday** [comment]
Metamask is not working for me, I am having the same issue!!

**Comment by bmiller59** [comment]
@mtsalenc I often keep my metamask disabled. Would be nice to know it was an option for the site even if it is not actively enabled. Thank you.

**Comment by mtsalenc** [comment]
Users were getting stuck with the connection because web3modal + walletconnect would keep a cached version of the connection.
On #392 we reset the connection so this should no longer be a problem.
