### ISSUE TITLE
Wrong challenge ID used when funding an appeal

### ISSUE THREAD

**Issue by fnanni-0** [Proof-Of-Humanity/proof-of-humanity-web#177]
This transaction was sent from the UI https://etherscan.io/tx/0x012f7cac2e8473772ff1b061a3d1d806f758485e95c5b6c117b4da6ed614ecab when a user tried to appeal Kleros ruling on this submission https://app.proofofhumanity.id/profile/0x00de4b13153673bcae2616b67bf822500d325fc3?network=mainnet. 

Note that challengeID was set to a very big number, but should have been 0.

**Comment by mtsalenc** [comment]
Looks like legacy code striking again. Same was happening with appeals.

**Comment by mtsalenc** [comment]
Closing this as it it was fixed here: https://github.com/Proof-Of-Humanity/proof-of-humanity-web/pull/165. My suspicion is that the user still had the old version of the app cached.

Reopen if it happens again

**Comment by fnanni-0** [comment]
@mtsalenc It's happening again with Kevin's dispute https://app.proofofhumanity.id/profile/0x00de4b13153673bcae2616b67bf822500d325fc3?network=mainnet. When funding the losing, challenge ID is wrong. It's working fine for the winning side though.

**Comment by fnanni-0** [comment]
This seems to be the bug: https://github.com/Proof-Of-Humanity/proof-of-humanity-web/blob/7f4380e45d29b581c4e71289ae7797c7b4e26587/components/appeal.js#L215. `id` should be `challengeID`

**Comment by mtsalenc** [comment]
Updated in https://github.com/Proof-Of-Humanity/proof-of-humanity-web/pull/186
