### ISSUE TITLE
Individual who was rejected and resubmitted is displayed as "Challenged Removal" while he is in "Pending registration"

### ISSUE THREAD

**Issue by clesaege** [Proof-Of-Humanity/proof-of-humanity-web#181]
See https://proof-of-humanity.netlify.app/profile/0x349FF1ea10E2560017BFbB942eFd1cC08100f8E3?network=mainnet

![image](https://user-images.githubusercontent.com/8873352/113325680-46b1a200-9308-11eb-9681-d26bbc6c8961.png)
![image](https://user-images.githubusercontent.com/8873352/113325705-4d401980-9308-11eb-9844-dc61913ae71d.png)

**Comment by tomeydemarcos** [comment]
That is my profile. It also says I been vouched but that vouch was from my challenged profile. 

Thanks for the help .

**Comment by tomeydemarcos** [comment]
@clesaege @mtsalenc ahi vi que el bug ahora corregido muestra que estoy en " vouching phase" pero debajo me aparece que fui Voucheado. ¿no es un error?

**Comment by mtsalenc** [comment]
Closing this as it has been fixed.
