### ISSUE TITLE
Cancell submission

### ISSUE THREAD

**Issue by Estebang188** [Proof-Of-Humanity/proof-of-humanity-web#199]
PoH = When I put cancel submission it remains processing (5 days ago)

![WhatsApp Image 2021-04-09 at 11 19 49](https://user-images.githubusercontent.com/82223439/114194285-b554b800-9925-11eb-8d7c-50e1f6f8198b.jpeg)

**Comment by hbarcelos** [comment]
Can you please provide a link to your profile?

**Comment by Estebang188** [comment]
Hello!

https://app.proofofhumanity.id/profile/0xC18a0cb531697212183c2D13b84885B630577b1A
[https://app.proofofhumanity.id/images/open-graph-image.png]<https://app.proofofhumanity.id/profile/0xC18a0cb531697212183c2D13b84885B630577b1A>
Proof of Humanity, a sybil-proof list of humans.<https://app.proofofhumanity.id/profile/0xC18a0cb531697212183c2D13b84885B630577b1A>
Proof of Humanity, a system combining webs of trust, with reverse Turing tests, and dispute resolution to create a sybil-proof list of humans.
app.proofofhumanity.id


Thanks!!!

________________________________
De: Henrique Barcelos ***@***.***>
Enviado: martes, 27 de abril de 2021 10:58
Para: Proof-Of-Humanity/proof-of-humanity-web ***@***.***>
Cc: Estebang188 ***@***.***>; Author ***@***.***>
Asunto: Re: [Proof-Of-Humanity/proof-of-humanity-web] Cancell submission (#199)


Can you please provide a link to your profile?

**Comment by mtsalenc** [comment]
This was likely a caching issue on the browser. Since then cache can no longer block the button.
