### ISSUE TITLE
Display Correct Number of Items According to the Filter

### ISSUE THREAD

**Issue by ferittuncer** [Proof-Of-Humanity/proof-of-humanity-web#202]
![Screenshot from 2021-04-10 03-24-21](https://user-images.githubusercontent.com/3106907/114252096-42daeb00-99ac-11eb-80ef-c247d1cdc8c4.png)

Currently, the number displayed belongs to option `all` no matter what filter is selected.

**Comment by alcercu** [comment]
Hello! I would like to tackle this issue, could you assign it to me? Thanks!
