### ISSUE TITLE
Improve profile submit UX

### ISSUE THREAD

**Issue by kdembler** [Proof-Of-Humanity/proof-of-humanity-web#206]
**Is your feature request related to a problem?**
The process of submitting a new profile (after clicking the `Submit` button) is pretty ambiguous to the user - you can see there's a spinner on the button and there are upload bars for files so something is happening. However, I think this could be much improved in terms of reporting to the user what's happening. This is a process that may require some waiting and may not be straight-froward to users coming from outside of the web3 world.

**Describe the solution you'd like.**
Something that guides the user through all the steps happening as part of the submission. I imagine there could be some kind of a modal dialog displayed above the page with a possible list of all steps and for sure the current step. Steps could be something like `Uploading files`, `Sending transaction`, `Waiting for confirmation`, `Done`. This could also tackle #109. Each step could also have some description so the user confidence is higher and wait is better understood.

This is a rough idea of what I have in mind. If that sounds like something you would be interested in, we can iron out the details and I'd be willing to work on that

**Comment by zalidthebur** [comment]
Just been through this process yesterday and I totally agree. I saw the files uploaded and then nothing. It leaves you wondering what is happening. Doing a search today for myself and I find my profile in the Vouching Phase as I would expect. I thought I would get an email as I had used the option, but it does not seem to be working as it keeps being unticked - I'll create a bug report for that if none has already been made.

**Comment by mtsalenc** [comment]
Yes this is definitely an area to improve in the app. Please reach out to us on slack.

**Comment by kdembler** [comment]
@mtsalenc sure thing. `#proofofhumanity` on Kleros Slack or is there some PoH-specific Slack?

**Comment by mtsalenc** [comment]
Please use the #dev channel, there are more people there
