### ISSUE TITLE
Number of vouches doesn't increase.

### ISSUE THREAD

**Issue by clesaege** [Proof-Of-Humanity/proof-of-humanity-web#21]
Number of vouches stays 0.
![image](https://user-images.githubusercontent.com/8873352/107673292-c5397e00-6c8d-11eb-8e6f-6eaf1e4397fe.png)

**Comment by epiqueras** [comment]
It was showing confirmed vouches after changeStateToPending.

I've changed it to show all vouches where the voucher doesn't have a used vouch and is still an active member.
