### ISSUE TITLE
Registered user who haven't started accruing can't start accruing

### ISSUE THREAD

**Issue by fnanni-0** [Proof-Of-Humanity/proof-of-humanity-web#210]
**Describe the Bug**
This is a rare case, but it already happened. When finalizing the registration, there are 2 txs being sent: executeRequest and startAccruing. startAccruing could fail if the gas limit is low. If this happens, the UI won't show a button to start accruing. A user reported this and said that he used the MetaMask gas limit estimation. Here is the tx https://etherscan.io/tx/0x2ea65b0f03ef10eb750b99e40d5d29261339f262f819379408d29590f2848634.  

**To Reproduce**
Set the gas limit so that executeRequest will go through but not startAccruing.

**Expected Behavior**
The UI should detect if a registered user is not accruing. If that's the case, show the old startAccruing button.

**Comment by clesaege** [comment]
In this case we should only show "start accruing" and only make the second call.

**Comment by herbstephens** [comment]
BUG case:  Steve Marshank

"Registered", but not accruing UBI.  Note: Steve is an early investor in Democracy Earth .. and may have been part of the original list (pre-vouched).  

profile:  https://app.proofofhumanity.id/profile/0x40c2a81ceb953bd09da61d867d9f02a0340f7344?network=mainnet

**Comment by delfinadiaza** [comment]
Hi! I have the same problem. Its been four days since I was vouched and I dont have the button to finalize adn start accruing. What can I do?

**Comment by fnanni-0** [comment]
@delfinadiaza is your profile in vouching phase? If yes, then you are in your voucher's waiting list. POH processes one vouch at a time, which means that you probably have to wait a few days.
