### ISSUE TITLE
Display Metacard on Twitter (and other Social Media) 

### ISSUE THREAD

**Issue by santisiri** [Proof-Of-Humanity/proof-of-humanity-web#214]
When I see links from [app.proofofhumanity.id](app.proofofhumanity.id) on Twitter or other social media, it doesn't display a metacard with the logo of Proof of Humanity or something more appealing to click. 

A metacard should display the POH logo. A step further would be to show the avatar of the profile pic on a metacard for a specific URL. 

<img width="534" alt="Screen Shot 2021-04-13 at 6 04 04 PM" src="https://user-images.githubusercontent.com/2153166/114584428-f54bd000-9c82-11eb-8997-ff1bdf3a60b6.png">

**Comment by ferittuncer** [comment]
I fixed this two weeks ago or so. Weird. Let me check again.

**Comment by ferittuncer** [comment]
https://github.com/Proof-Of-Humanity/proof-of-humanity-web/pull/161

**Comment by ferittuncer** [comment]
https://app.proofofhumanity.id/images/open-graph-image.png

**Comment by ferittuncer** [comment]
Relative URLs not supported that's why it does not work.

This does not work either: https://github.com/kleros/website/issues/83
