### ISSUE TITLE
Submit doesn't work

### ISSUE THREAD

**Issue by TobiasFri** [Proof-Of-Humanity/proof-of-humanity-web#218]
I'm trying to submit my profile but the operation is never completed. ETH funds were already transfered from my account and I don't know the status of the transaction. My address is: 0xa83A35aF95a0fdf6754C44627D59205069E135df

**Comment by eperoche** [comment]
Hi!
I am have the same problem.  My address is: 0xc0A51ba375fa698e877F42b2C332fe14A2aD36c3

**Comment by jmartinez042** [comment]
Hi, I have the same problem.
My address is: 0xD0DB216E951c065F5dB2269C6EaFB69A8B61Ee12

**Comment by felipecontarino** [comment]
DID YOU WORK IT OUT?

**Comment by eperoche** [comment]
Yes, this was solved in one day.

**Comment by mtsalenc** [comment]
Closing this as it was probably just mining delay. Reopen if you find a bug in the submission.
