### ISSUE TITLE
Successful Vouch Tx but vouch is not displayed on the UI 

### ISSUE THREAD

**Issue by jragosa** [Proof-Of-Humanity/proof-of-humanity-web#219]
[Profile A](https://app.proofofhumanity.id/profile/0x3b3CC878FD599A84aD3f0BaE1bE83aE6Da363582) vouched for [Profile B](https://app.proofofhumanity.id/profile/0x914985a71b321aacc40e47d1c66286bc7a0e5432?network=mainnet) in this [Tx](https://etherscan.io/tx/0x3d7d5aa6ed07933f7810402c1d7cadbae927799484aec79bc94f5cf88dedfc0c) but the vouch is not showing in the UI or on the subgraph.

**Comment by mtsalenc** [comment]
This is due to https://status.thegraph.com/incidents/15f1sq5gk1v4. Should sort itself out soon.

**Comment by mtsalenc** [comment]
Closing this as it is not a PoH bug but just an outage on the graph.
