### ISSUE TITLE
Webcam Issue

### ISSUE THREAD

**Issue by ferittuncer** [Proof-Of-Humanity/proof-of-humanity-web#22]
Ubuntu 20
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36

Webcam sometimes dont work.
https://ipfs.kleros.io/ipfs/QmPxyNESzcK4SvgcSjQ1avwCsBksmkzazTxJCD13hojtoo

**Comment by epiqueras** [comment]
Only sometimes?

Do you have an error log or something? I don't have an Ubuntu machine to replicate this on.

We've tested on Safari, Chrome, Firefox, and Brave, and it works on Mac and Windows.
