### ISSUE TITLE
Profile Submission - Video and Photo Upload Bars Keep Saying Uploading Until Tx is Confirmed

### ISSUE THREAD

**Issue by ferittuncer** [Proof-Of-Humanity/proof-of-humanity-web#223]
Video and photo upload bars are nice, but they don't signal success until the transaction is confirmed. This is a bad user experience as it misguides users to think that the upload has not completed and the transaction has started with incomplete profile information.

**Comment by kdembler** [comment]
Please take a look at #206

**Comment by hbarcelos** [comment]
It does change the color, but yeah, maybe the text should be changed as well.
