### ISSUE TITLE
Pagination is Misleading

### ISSUE THREAD

**Issue by ferittuncer** [Proof-Of-Humanity/proof-of-humanity-web#23]
Pagination is showing 1 even when there are more pages, is this intended? Gives the false impression that there is only 1 page.

https://ipfs.kleros.io/ipfs/QmVCVxNCXc3ncp3Cx3K5v4KAaDp9QKcHbojohGZt46U6q9

**Comment by epiqueras** [comment]
Yeah, this is because The Graph doesn't natively support pagination. We have to look ahead to a constant number of items explicitly.
