### ISSUE TITLE
Vouching is delayed. Profiles are not updating.

### ISSUE THREAD

**Issue by carrymaster** [Proof-Of-Humanity/proof-of-humanity-web#232]
**Describe the Bug**
I have vouched 3 hours ago but it isn't impact on my profile. On the telegram group there is a bunch of users reporting the same behaviour. Some of them are waiting from a day ago.

Is it normal? Could be an issue related to the new way of free gas vouching?

**To Reproduce**
1) Click on vouch on a profile.
2) Accept the signature.
3) Submit vouch.

No impact on the profile.

**Expected Behavior**
Impact on the vouched profile in a couple of hours.

**Comment by mtsalenc** [comment]
Can you please check that this is still reproducible? The vouch should be detected immediately now.

**Comment by carrymaster** [comment]
@mtsalenc working for me, closing the issue
thanks!
