### ISSUE TITLE
UI Crash On Page Load

### ISSUE THREAD

**Issue by ferittuncer** [Proof-Of-Humanity/proof-of-humanity-web#25]
Crashing url: https://proof-of-humanity.netlify.app/profile/0x0b6b4566f9ac32e06c309bcbbd906a380237cb1e?network=kovan

This is the failing network request:
![Screenshot from 2021-02-11 19-59-23](https://user-images.githubusercontent.com/3106907/107674358-f1fa8f00-6ca7-11eb-9209-07cc8b124dc0.png)

https://ipfs.kleros.io/ipfs/QmPaqiXGFiVeTA3TcRpysZmRUYusSGy8MUPtkimKPUsjYc

**Comment by epiqueras** [comment]
Fixed.

It was actually a BN rounding issue.
