### ISSUE TITLE
Insane gas limit when attempting to Fund Submission

### ISSUE THREAD

**Issue by mmiguerodriguez** [Proof-Of-Humanity/proof-of-humanity-web#256]
**Describe the Bug**
I want to fund a submission and the gas prices are insane (6x what I should send which is 0.157)

**To Reproduce**
Attempt to fund a submission

**Expected Behavior**
Gas price should be lower

**Screenshots**
![image](https://user-images.githubusercontent.com/12092151/115993276-7cb11180-a5a8-11eb-8617-abc5372f4d9b.png)

**Device and Browser Information**
Google Chrome with Metamask Extension

**Comment by hbarcelos** [comment]
This is most likely a transaction that will fail.
Can you please provide a link to the profile you are trying to fund?

**Comment by mmiguerodriguez** [comment]
> This is most likely a transaction that will fail.
> Can you please provide a link to the profile you are trying to fund?

It was that! Sorry for the inconvenience.
