### ISSUE TITLE
Visual Issue On Number of Vouchers Indicator

### ISSUE THREAD

**Issue by ferittuncer** [Proof-Of-Humanity/proof-of-humanity-web#26]
Screenshot from a desktop resolution:
![Screenshot from 2021-02-11 20-11-00](https://user-images.githubusercontent.com/3106907/107674852-7b11c600-6ca8-11eb-8dfb-cd25a774ac51.png)

Needs more space.

**Comment by epiqueras** [comment]
Fixed
