### ISSUE TITLE
Video Blurry can't withdraw submission or upload new video!

### ISSUE THREAD

**Issue by AnthonyWSmith** [Proof-Of-Humanity/proof-of-humanity-web#260]
Hi I spent several hours following the guidelines. I submitted and thought my video was good but when I looked at it after uploading , a friend was hesitant to vouch for me in case it's too blurry and it cost him. I followed the instructions to withdraw submission but it said it can't verify that my gas fee was mined .  Here's the link to my submission . Please advise I don't have much and am concerned I will lose the  Eth that is being held in reserve!  Do you think it's adequate to get verified or not is the question as I'm not sure and scared to lose my deposit. 

https://app.proofofhumanity.id/profile/0x9c2177026a9c0396EF0D209d892EecE513a3eAe3

**Comment by mtsalenc** [comment]
Anthony, looks like your transaction was never minde probably due to low gas fee. You should click the "Cancel Submission" again and sign the transaction.

Please reach out for more help here: https://t.me/pohDebug

**Comment by AnthonyWSmith** [comment]
Yes I hit cancel and it turns red and spins but nothing ever happens after that and I have plenty of ETH in my metamask? I've tried restarting my mac laptop, using different browsers (chrome, safari, or brave), ipads, phone, and desktop. Still I cannot cancel it! I'm not a developer but I'm also not tech illiterate as I do a lot of stuff with cypto. I honestly don't know what to do. Here's my link and I can't cancel it. Please help?  Can I have it manually deleted and so I can submit again??

https://app.proofofhumanity.id/profile/0x9c2177026a9c0396EF0D209d892EecE513a3eAe3
