### ISSUE TITLE
Funding % is wrong for submissions which are fully funded after deposit update

### ISSUE THREAD

**Issue by clesaege** [Proof-Of-Humanity/proof-of-humanity-web#263]
![image](https://user-images.githubusercontent.com/8873352/116707695-7a8eee80-a9be-11eb-96e5-732a508215ba.png)

They don't look fully funded due the deposit having been increased but they are already funded so no need to add anything for them.

**Comment by mtsalenc** [comment]
Solved in https://github.com/Proof-Of-Humanity/proof-of-humanity-web/pull/266.
