### ISSUE TITLE
Cannot see some profiles

### ISSUE THREAD

**Issue by fnanni-0** [Proof-Of-Humanity/proof-of-humanity-web#268]
Some profiles cannot be seen when opened. See:

https://app.proofofhumanity.id/profile/0xe2a0a12ee0e3080810bf9a416f3471f2530950e7
https://app.proofofhumanity.id/profile/0x05f543170e58214b0f050e99bfb5b23ff02445a8
https://app.proofofhumanity.id/profile/0xa951cae9d824273b3228bfb4ce34a6868980024e
https://app.proofofhumanity.id/profile/0x56abe5a99b71947384a261bfbfc25bc90262891f

There is an error shown in the console: "Error: <svg> attribute height: Expected length, "auto"."

**Comment by diegoflores111** [comment]
I have the same issue, I can't see my own profile I submitted.

**Comment by Lucas-bck** [comment]
I have the same issue, I can't see my own profile I re submitted.

https://app.proofofhumanity.id/profile/0x410c92BCE3CBE850499F4373029fF19EFFC11748
