### ISSUE TITLE
can't swtich to Self Fund default option 

### ISSUE THREAD

**Issue by Lucas-bck** [Proof-Of-Humanity/proof-of-humanity-web#273]
When submitting my profile I have selected by mistake crowdfound deposite mode. 
Would appreciate if you can switch to Self Fund default option ir order to move forward with my registration. Thanks!-

My profile:
https://app.proofofhumanity.id/profile/0x410c92BCE3CBE850499F4373029fF19EFFC11748

**Comment by mtsalenc** [comment]
It is not possible to "switch to self fund". What you can do is just fund your own submission. It'll work just as the same.

**Comment by mtsalenc** [comment]
@Lucas-bck did you manage to do it?

**Comment by Lucas-bck** [comment]
I can't afford funding. How can i request for help on that?. Thanks

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by mtsalenc** [comment]
You may ask in the telegram crowdvouching group (https://t.me/joinchat/G2FZNtddAUhlMmJh), someone might be willing to pay for you.
