### ISSUE TITLE
Finalize registration and start accruing

### ISSUE THREAD

**Issue by guilletok** [Proof-Of-Humanity/proof-of-humanity-web#275]
Hi, I cannot finalize the registration process. The link has been loading for two days, and the site hasn't connected with my wallet. What should I do? Thanks!

**Comment by mtsalenc** [comment]
Can you please provide a link to your profile? It might be the case that your tx never minded due to a spike in gas fees.

**Comment by guilletok** [comment]
> Can you please provide a link to your profile? It might be the case that your tx never minded due to a spike in gas fees.

Sure, here you are: https://app.proofofhumanity.id/profile/0x4530c696fb6c356153a1BFaDDD52d9DCb5613152

Thanks!

**Comment by churitof** [comment]
Hi! i have the same problem..

here is my profiles link: https://app.proofofhumanity.id/profile/0x1362B28b1dAAAea07380D4d7bD0b57Db79e2628D


thanks!!

**Comment by mtsalenc** [comment]
What browser and wallet are you using?

**Comment by churitof** [comment]
I'm using Chromecast and MetaMask

**Comment by mtsalenc** [comment]
Do you mean google chrome? Please try with Firefox + Metamask.

**Comment by mtsalenc** [comment]
> > Can you please provide a link to your profile? It might be the case that your tx never minded due to a spike in gas fees.
> 
> Sure, here you are: https://app.proofofhumanity.id/profile/0x4530c696fb6c356153a1BFaDDD52d9DCb5613152
> 
> Thanks!

Looks like your profile is registered. Is your issue solved?

**Comment by guilletok** [comment]
> > > Can you please provide a link to your profile? It might be the case that your tx never minded due to a spike in gas fees.
> > 
> > 
> > Sure, here you are: https://app.proofofhumanity.id/profile/0x4530c696fb6c356153a1BFaDDD52d9DCb5613152
> > Thanks!
> 
> Looks like your profile is registered. Is your issue solved?

Yes! Thanks! I just entered to close the issue. I cleaned all cookies and cache info, and I could do it. Thanks
