### ISSUE TITLE
Submit Profile stuck to loading 

### ISSUE THREAD

**Issue by lorepieri8** [Proof-Of-Humanity/proof-of-humanity-web#276]
**Describe the Bug**

Submit Profile stuck to loading.
I'm inserting initial deposit zero (crowdfunding) and the associated metamask account has 0 balance. 
Do I need to have >0 balance to submit? 

**To Reproduce**

Fill all the forms in the proofofhumanity app and click submit. 

**Expected Behavior**
Metamask sign confirmation? Not sure.

**Device and Browser Information**
Chrome, MacOS.

**Comment by mtsalenc** [comment]
Yes, even if you do not pay for the deposit you have to pay gas fees to miners.

**Comment by mtsalenc** [comment]
Did you manage to submit? If not please reopen this.
