### ISSUE TITLE
Enable Checkbox Position

### ISSUE THREAD

**Issue by ferittuncer** [Proof-Of-Humanity/proof-of-humanity-web#28]
Probably the intended spot for checkbox is after the enable label.
![Screenshot from 2021-02-11 19-16-32](https://user-images.githubusercontent.com/3106907/107675094-bf04cb00-6ca8-11eb-9ab9-c1142556e776.png)

**Comment by epiqueras** [comment]
No, not really. The design was made for multiple checkboxes.
