### ISSUE TITLE
I CANT PASS THE SUBMIT PROFILE.

### ISSUE THREAD

**Issue by felipecontarino** [Proof-Of-Humanity/proof-of-humanity-web#283]
I DID EVERYTHING THE FIRST TIME AND METAMASK ASK ME TO SIGN THE SELFUND, I SIGN IT, BUT NOTHING HAPPENED.

NOW IM TRYING BUT I ONLY FINISH ON PHOTO AND VIDEO UPLOADING, BUT NOTHING BEYOND THAT. 
I CLICK ON SUBMIT AND IT NOT CONNECT TO METAMASK TO MAKE THE SELF FUND.

ANYONE CAN HELP?

**Comment by felipecontarino** [comment]
![image](https://user-images.githubusercontent.com/83773932/117320252-6cc7e600-ae62-11eb-869a-a7d6d25c6e69.jpg)

**Comment by clesaege** [comment]
No shouting
