### ISSUE TITLE
PLEASE HELP. I DID A BIG MISTAKE.

### ISSUE THREAD

**Issue by felipecontarino** [Proof-Of-Humanity/proof-of-humanity-web#284]
I WAS HAVING PROBLEMS WITH THE SUBMIT, SO I CHANGED TO ANOTHER WALLET TO TRY IF IT WORKS.

I REALIZED THE SUBMIT AND PAY THE ENTIRE FUND BUT I FORGOT TO CHANGE MY VIDEO WITH THE NEW WALLET!!!!

ITS THERE ANYWAY THAT WE CAN SOLVE IT?? I DONT WANT TO LOSE MY MONEY!!

**Comment by clesaege** [comment]
No shouting.
