### ISSUE TITLE
Video uploaded appears "washed out" to some users

### ISSUE THREAD

**Issue by marcgug** [Proof-Of-Humanity/proof-of-humanity-web#287]
**Describe the Bug**

The video that I uploaded appears fine on my computer (Mac OS, Chrome 90) and other users computers, but for some users, the video appears "washed out" and the address is not legible. This may have caused my submission to be challenged. Here is the profile:

https://app.proofofhumanity.id/profile/0xaea8c963000578d7f74699116776f8b39024d2e4

**To Reproduce**

1. Shoot a video on an iPhone on iOS 14.5.1
2. Convert that video to a .mp4 file using handbrake on a computer running MacOS 11.3 on an Apple m1 chip.
3. Upload the video as part of a profile submission.

**Expected Behavior**

The video appears with the same brightness levels on all browsers that view it (which is the same as what I saw when previewing and uploading the video).

**Screenshots**

Here is how it appears to me and some other users:

![Image 2021-05-06 16-29-58](https://user-images.githubusercontent.com/8808/117361697-fc2fc200-ae7f-11eb-83f8-69b912cf9544.jpg)

Here is how it appears to at least one user (using Chrome Version 90.0.4430.93 (Official Build) (64-bit) - on a Windows 10 machine):
![Image 2021-05-06 16-31-48](https://user-images.githubusercontent.com/8808/117361970-516bd380-ae80-11eb-9220-a8c0c89f733b.jpg)

**Device and Browser Information**

I uploaded the video from a computer running MacOS 11.3, with an Apple M1 chip on Chrome 90.0.4430.93 (Official Build) (arm64).

**Comment by mtsalenc** [comment]
This is because the video was recorded with Dolby Vision HDR enabled. 

Closing this because it is not an issue with proof of humanity. Affects all displays that cannot properly display this video format.
