### ISSUE TITLE
Page keeps reloading when wrong network is selected in Metamask.

### ISSUE THREAD

**Issue by virids** [Proof-Of-Humanity/proof-of-humanity-web#291]
**To Reproduce**
I encountered this issue when my Metamask was set to BSC network and got me confused for a while until I figured out what was wrong. It's easily reproducible if you just switch networks. Upon returning to Ethereun Mainnet functionality is restored.

**Screenshots**
![Peek 2021-05-09 11-33](https://user-images.githubusercontent.com/6049810/117567086-a3983900-b0ba-11eb-869c-2e7e4dd5efb6.gif)

**Device and Browser Information**
Ubuntu, Firefox, Metamask.

**Comment by mycoBici** [comment]
Same issue. Very nerve racking and not obvious for most users. Should display a message that it can't connect to wallet rather than just going berserk
