### ISSUE TITLE
Cannot Submit profile with Metamask

### ISSUE THREAD

**Issue by MrMorito** [Proof-Of-Humanity/proof-of-humanity-web#302]
**Describe the Bug** Cannot Fsubmit profile Metamask. The "submit" button keeps spinning, i tryed with edge, chrome, my laptop and in my cell phone. all teh same. i have ETH in my metamask wallet

**To Reproduce**

**Expected Behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/84154674/118183976-26015f80-b411-11eb-9230-c82b787bb752.png)

**Device and Browser Information**

**Comment by pablotocco** [comment]
I'm having the same problem. What is the solution?
<img width="1440" alt="Captura de Pantalla 2021-05-21 a la(s) 13 00 32" src="https://user-images.githubusercontent.com/84586006/119166046-8d806600-ba34-11eb-9fbd-97b3177963c3.png">

**Comment by mtsalenc** [comment]
The problem was due to using WalletConnect. Please reopen the issue if you face this again.
