### ISSUE TITLE
Improve English text of "Seize UBI" label

### ISSUE THREAD

**Issue by dogweather** [Proof-Of-Humanity/proof-of-humanity-web#303]
As a native English speaker, I'm not sure what this button label does. "Seize" in this sense has a negative connotation. E.g., "The police seized all the assets they discovered."

What function does the button have? I can help with the translation.

**Comment by mtsalenc** [comment]
The function serves to "take away" someone's UBI after their profile was removed from the registry. This is the reward people get from actively looking for profiles that should no longer be in the registry (because for example, the person died).

On which profile did you see this?

**Comment by dogweather** [comment]
Ah, I'm not sure which it was.

**Comment by mtsalenc** [comment]
No problem... This is actually an outstanding UX issue. I'm looking for better labels for this button so I'll leave this open.
