### ISSUE TITLE
Present text to properly set users' expectations

### ISSUE THREAD

**Issue by dogweather** [Proof-Of-Humanity/proof-of-humanity-web#304]
**Is your feature request related to a problem?**

Yes, users' expectations aren't properly set for using the web app.

Currently, users only find out about new Eth transactions and gas fees _after_ they've entrusted the app with their deposit and put it at risk. It's very unfair, uncompassionate, and counter to the program's espoused values.

**Describe the solution you'd like.**

The site would include a section, "What you'll need to register". It will include something along the lines of, "The equivalent of USD $1,000, of which you'll spend $2-400 on transaction ('gas') fees."

**Comment by clesaege** [comment]
Gas prices are in all ETH dapps, moreover they always change based on market demand so hardcoding anything would be really useful.
I think efforts are better spent at working on L2 than trying to provide gas analytics on L1.
