### ISSUE TITLE
In voting history  the word "Round" is missing

### ISSUE THREAD

**Issue by clesaege** [Proof-Of-Humanity/proof-of-humanity-web#31]
Figma
![image](https://user-images.githubusercontent.com/8873352/107677049-b785f780-6c91-11eb-9d6b-1c01429a32a4.png)

Current UI
![image](https://user-images.githubusercontent.com/8873352/107677088-c5d41380-6c91-11eb-87d2-2923cdc58353.png)

**Comment by epiqueras** [comment]
Fixed
