### ISSUE TITLE
Evidence/metaevidence not displaying correctly in court

### ISSUE THREAD

**Issue by whwgeorge** [Proof-Of-Humanity/proof-of-humanity-web#32]
**Describe the Bug**

When a challenge is created (at least in the existing Kovan version), the evidence related to a proof of humanity case, namely the person's photo and video, the reason for challenge, etc, are not displayed on the court. Also the options for jurors are "Yes" and "No".

**To Reproduce**

**Expected Behavior**

**Screenshots**

![noevidence](https://user-images.githubusercontent.com/32513740/107677638-7d543000-6c68-11eb-8dee-44e73d672c27.png)

**Device and Browser Information**

**Comment by epiqueras** [comment]
Please open this on https://github.com/kleros/court.

**Comment by clesaege** [comment]
It works for other dapps so I'm not sure the court is the issue there. I reopen here so we can keep track of all issues impending POH launch.
For example the label "Yes" and "No" are probably related to the metaevidence document.

**Comment by epiqueras** [comment]
These are the docs for reference:

```json
{
  "category": "Curated List",
  "title": "Proof of Humanity Clearing Request",
  "description": "A request to remove the specified entry from a list of provable humans.",
  "question": "Should the request to remove be accepted?",
  "rulingOptions": {
    "type": "single-select",
    "titles": ["Yes", "No"],
    "descriptions": [
      "Accept the request to remove the entry.",
      "Deny the request."
    ]
  }
}
{
  "category": "Curated List",
  "title": "Proof of Humanity Registration Request",
  "description": "A request to register the specified entry to a list of provable humans.",
  "question": "Should the request to register be accepted?",
  "rulingOptions": {
    "type": "single-select",
    "titles": ["Yes", "No"],
    "descriptions": [
      "Accept the request to register the entry.",
      "Deny the request."
    ]
  }
}
```

**Comment by epiqueras** [comment]
Any weird behavior here should be fixed by https://github.com/kleros/court/pull/153.

Let's close this as it's not an issue anymore.

When @jragosa finishes the primary document and we upload it in new meta evidence, we can change these titles and descriptions to whatever we want, just like with all the other apps.
