### ISSUE TITLE
High gas fee and 0 eth back for registering

### ISSUE THREAD

**Issue by GuilleMM80** [Proof-Of-Humanity/proof-of-humanity-web#321]
**Describe the Bug**
Hi, it's impossible to pay so high eth gas fee and for receiveing 0 eth back from the initial payment? 
**To Reproduce**
link: https://app.proofofhumanity.id/profile/0x231C6e2bdc1b4Df5abFdbD4F8cd27C47725eCf6C

**Expected Behavior**
Be registered and have my eth back
**Screenshots**
![Screenshot_20210518-112046_Argent](https://user-images.githubusercontent.com/81648523/118669264-fe711500-b7cb-11eb-9d5b-91fbfc4e7175.jpg)

**Device and Browser Information**
PC. Chrome, Opera and Firefox (last versions of each)

**Comment by mtsalenc** [comment]
This is not a bug, you need more ETH to pay the fee. This transaction will also give your 0.157 ETH back.

**Comment by GuilleMM80** [comment]
But i've tried to do it and i read 0 eth, not 0,157. That's why i've
written as a bug. Sorry for that but i have no other way to ask for it.

**Comment by mtsalenc** [comment]
Oh no problem, 0 is the amount of value that is its asking to send in the transaction (which is correct) but PoH will give you back 0.157 (assuming you funded your own submission when you submitted your profile).

What wallet is this by the way?

**Comment by GuilleMM80** [comment]
Argent wallet. I regret having used that wallet. It's insane the gas fee
and you can't change many parameters.
