### ISSUE TITLE
Devs: updated targeted Node version

### ISSUE THREAD

**Issue by justinkalland** [Proof-Of-Humanity/proof-of-humanity-web#323]
Please see [PR 209](https://github.com/Proof-Of-Humanity/proof-of-humanity-web/pull/309) and [PR 316](https://github.com/Proof-Of-Humanity/proof-of-humanity-web/pull/316) for context.

--

The Node version being used by the Netlify build is 10 (set via `./.node-version`). This version is no longer supported 😬. The new Active LTS is Node 14. In addition we do not provide a target version `.nvmrc` - an important configuration for IDEs / hosting / tools / etc.

My intention on this issue is to reach consensus on a [target Node version](https://nodejs.org/en/about/releases/).

My vote would be Node 16 (both for `.nvmrc` and `./.node-version`

**Comment by justinkalland** [comment]
@RoboTeddy

**Comment by RoboTeddy** [comment]
I agree that it would be good to pin a specific version which is actively supported using both `.nvmrc` and `.node-version` — I don't have any strong preferences of which version is picked (Node 16 sounds fine to me though)

@mtsalenc what do you think?

**Comment by justinkalland** [comment]
For me 16 makes the most sense, but I would also be fine with 14.

**Comment by mtsalenc** [comment]
`npm install` won't run to completion with node@16, but it will run with node@14 so I am setting that as the latest version.

Also added `.nvmrc` and `volta` to package.json

**Comment by justinkalland** [comment]
Interesting, runs on my machine fine with 16 - but 14 is also good! Thanks
