### ISSUE TITLE
I can't finish my registration with metamask

### ISSUE THREAD

**Issue by pablotocco** [Proof-Of-Humanity/proof-of-humanity-web#328]
**Describe the Bug**

**To Reproduce**

**Expected Behavior**

**Screenshots**

**Device and Browser Information**

**Comment by pablotocco** [comment]
I am not able to finish my registration. I am using Metamask.
I need a solution.
The video and the photo are uploaded, but it never ends.

**Comment by pablotocco** [comment]
<img width="1440" alt="Captura de Pantalla 2021-05-21 a la(s) 13 00 32" src="https://user-images.githubusercontent.com/84586006/119166342-dfc18700-ba34-11eb-91e4-435452f964ce.png">

**Comment by mtsalenc** [comment]
As we discussed in DMs, this was due to PoH being connected via WalletConnect. Using MetaMask directly should fix the issue, please reopen if the issue persists.
