### ISSUE TITLE
Submitting evidence doesn't work

### ISSUE THREAD

**Issue by clesaege** [Proof-Of-Humanity/proof-of-humanity-web#33]
Evidence are not displayed in POH UI nor in the court UI.
This is the case for both plaintext and pdf evidence.
https://proof-of-humanity.netlify.app/profile/0x10e20e1ba384a80fb27084230fb18a8729b29397?network=kovan

**Comment by epiqueras** [comment]
<img width="1075" alt="Screen Shot 2021-02-11 at 10 47 46 AM" src="https://user-images.githubusercontent.com/19157096/107683585-96ec7c00-6c56-11eb-8615-a98b24a3126b.png">

**Comment by clesaege** [comment]
OK, it's just slow to be displayed for the POH dapp.
But it didn't display them in the court dapp https://court.kleros.io/cases/807

**Comment by epiqueras** [comment]
That is the issue with Archon I reported to @mtsalenc and @hbarcelos. We should track it there.

**Comment by clesaege** [comment]
Could you point to this issue?
Even if the issue is on archon side, we need to keep track of it as one of the issue to be fixed before launching.

**Comment by epiqueras** [comment]
It seems fixed in Archon. Court just needs an update and redeploy.

@mtsalenc @hbarcelos

**Comment by epiqueras** [comment]
I just did it: https://github.com/kleros/court/pull/153
