### ISSUE TITLE
Can't access profile on proofofhumanity

### ISSUE THREAD

**Issue by nlarotta1** [Proof-Of-Humanity/proof-of-humanity-web#336]
**Can't access profile on proofofhumanity**

**Login into proof of humanity, click on profile**

Actual behavior, the profile shows up and immediately the message shows up "an unexpected error has occured

**It is possible to see the profile**

**Screenshots
![Screenshot_20210525-204107_MetaMask](https://user-images.githubusercontent.com/84806357/119551142-96a56600-bd99-11eb-9174-de144fd0413f.jpg)
**

**Android and Chrome explorer**

Same issue as reported here: https://github.com/Proof-Of-Humanity/proof-of-humanity-web/issues/269

Link to profile: https://app.proofofhumanity.id/profile/0xcA841482B57Bdc995F35E7e8c4466cCb94C30cC3

**Comment by mtsalenc** [comment]
The profile looks accessible now.

There was an outage on subgraph hosted service (used by PoH) this morning. 
Please try again and reopen if the issue persists.
