### ISSUE TITLE
Resubmit Button for Removed Accounts

### ISSUE THREAD

**Issue by whwgeorge** [Proof-Of-Humanity/proof-of-humanity-web#34]
**Is your feature request related to a problem?**

Currently there appears to be no mechanism in the UI to resubmit a profile once it is removed, see screenshot below. Conceivably someone might want to bring back an expired account.

![resubmitbutton](https://user-images.githubusercontent.com/32513740/107679155-35cea380-6c6a-11eb-9ae9-d73a7f30ed8a.png)

**Describe the solution you'd like.**

**Describe alternatives you've considered.**

**Comment by epiqueras** [comment]
You should see the button now if you look at the page with that account active.
