### ISSUE TITLE
Lost initial funding deposit after profile started to accrue UBI

### ISSUE THREAD

**Issue by triiips** [Proof-Of-Humanity/proof-of-humanity-web#345]
**Describe the Bug**
Profile owner contributed 0.1 eth while I contributed 0.084 eth. After the profile was successfully registered, the owner received their 0.1 eth back, but I did not get anything.

**To Reproduce**

Submit account with 0.1 eth deposit
https://etherscan.io/tx/0xa0f203f9e3b7f31cdfac4742fa95eee2c0c1e1e3eec3a804a2b255da0617c523

Crowdfund 0.084 eth
https://etherscan.io/tx/0x2ec01f6bad7161cd1907a292ad5e2da96d57cf6eec092f3e50f7c18e1e4ad33e/advanced

Complete registration but only account owner receives deposit refund
https://etherscan.io/tx/0x57648db72ec33e5c5645412ca5344f64d858d13f3cfb189f3564c7dd37fbffcf
("Although one or more Error Occurred [Reverted] Contract Execution Completed")

**Expected Behavior**
0.084 eth is expected to be returned to 0x73a8a4990996CD7647458d33F28f813b64562751 under normal circumstances.

**Screenshots**
![image](https://user-images.githubusercontent.com/83733789/119688835-917e0080-be05-11eb-8972-98709f7b668b.png)

**Comment by mtsalenc** [comment]
Your funds are safe.

Crowdfunded contributions are not refunded in the transaction final transaction. Instead, they are withdrawn via the withdraw contributions function. You can wither:
- Wait for a convenience bot that withdraws this for you (cheaper, wait longer)
- Withdraw it yourself (you have to pay gas, get your contribution immediately)

The error is harmless:
The last step moves a profile into the pending state as described here: https://twitter.com/mtsalenc/status/1385256231938396167?s=20. Occasionally, two people submit a transaction advancing the same profile, so the second one to be mined fails partially.
