### ISSUE TITLE
Cancel submission doesn't do anything

### ISSUE THREAD

**Issue by gpozzi** [Proof-Of-Humanity/proof-of-humanity-web#353]
**Describe the Bug**
When I put cancel submission it remains processing (14 days ago). I don't have pending transactions on Metamask

**To Reproduce**
Submit video, then cancel submission.

**Expected Behavior**
Submission disappears from POH. No pending submission to cancel

**Screenshots**
![image](https://user-images.githubusercontent.com/52865532/120239711-3e58e300-c235-11eb-8141-b763ff9fa063.png)

**Device and Browser Information**
Chrome 90.0.4430.212

**Link**
https://app.proofofhumanity.id/profile/0x5a8A6D57ccDf220416C8138Bc22748dd18B44FB0

**Comment by mtsalenc** [comment]
It looks like there was some buggy cache blocking the button.

Please try clicking the button again now.
