### ISSUE TITLE
The "Seize UBI" button should only appear on Expired profile

### ISSUE THREAD

**Issue by jragosa** [Proof-Of-Humanity/proof-of-humanity-web#36]
Currently, the "Seize UBI" button is displayed even on "Registered" profile not yet expired. Some users could try to seize the UBI accrued even if their Tx will fail. It would be better for the button to be only displayed when actionable.

![image](https://user-images.githubusercontent.com/34345327/107750846-e0070380-6d1c-11eb-82ca-dd721ec791c2.png)

**Comment by epiqueras** [comment]
Fixed

The issue was actually that expiration status was flipped.
