### ISSUE TITLE
My status doesn't change

### ISSUE THREAD

**Issue by mrazzetti** [Proof-Of-Humanity/proof-of-humanity-web#361]
I had to register again because my first attempt was rejected.

I uploaded the video, get my vouch 5 days ago and my status continue in Vouching Phase.
Yesterday I get another vouch and also click in "Advance to pending" button but it seems that it didn't work because it continue in the status in pending in Metamask.

I cancel the transaction in Metamask to click again in "Advance to Pending" but I cannot do it because the botton is bug, I think

![imagen](https://user-images.githubusercontent.com/85292128/120642688-9406d880-c44b-11eb-93b8-abe3ffbeffc3.png)

![imagen](https://user-images.githubusercontent.com/85292128/120642724-a08b3100-c44b-11eb-89b5-307ceffd4ff0.png)

The botton is like "uploading" but notthing happen. 

Anyone can help me?

**Comment by mtsalenc** [comment]
@mrazzetti Do you mind sharing your profile address? If not we can coordinate privately.
