### ISSUE TITLE
UBI drips on profiles not in Registered status

### ISSUE THREAD

**Issue by NingF23** [Proof-Of-Humanity/proof-of-humanity-web#365]
**Describe the Bug**
UBI appears to drip on profiles both in **Vouching** and **Pending Registration** stages but the amt resets upon page refresh

**To Reproduce**
Happens in all profiles randomly checked

**Expected Behavior**
UBI should be at 0

**Screenshots**
Vouching
![image](https://user-images.githubusercontent.com/83063111/120984124-ebd77380-c7ac-11eb-9e58-6869d6bca378.png)

https://app.proofofhumanity.id/profile/0xea957dcdd3718084b1c0fea8747799813e712044

Pending Registration
![image](https://user-images.githubusercontent.com/83063111/120984001-ce0a0e80-c7ac-11eb-9726-e72d419d1b3d.png)
https://app.proofofhumanity.id/profile/0xf0e4a8f6e0c364797ea2fd3c87c6edcbf6d43914

**Device and Browser Information**
All devices and browsers

**Comment by mtsalenc** [comment]
Fixed in #367
