### ISSUE TITLE
Error when finalizing registration

### ISSUE THREAD

**Issue by mjvallone** [Proof-Of-Humanity/proof-of-humanity-web#368]
**Describe the Bug**
I'm in "Pending Registration" state, when I click in the button "Finalize registration and start accruing" I see no changes on the website.
But this is what I see in the browser console:
![image](https://user-images.githubusercontent.com/961296/121238142-29500580-c86e-11eb-8cf3-4b0ca276561b.png)

**Expected Behavior**
I was expecting to conclude my registration.

**Device and Browser Information**
Google Chrome - Version 91.0.4472.77 (Official Build) (64-bit)
Ubuntu 20.04.2 LTS

**Comment by mjvallone** [comment]
I could finalize it! I've found (I googled it) that I needed to reset my metamask account :/

**Comment by mtsalenc** [comment]
Closing this as it was not a UI issue.
