### ISSUE TITLE
Enhancement to initial contribution section UX

### ISSUE THREAD

**Issue by jragosa** [Proof-Of-Humanity/proof-of-humanity-web#37]
I still find this section quite confusing:
![image](https://user-images.githubusercontent.com/34345327/107752509-23627180-6d1f-11eb-8ad5-61f82c7c2c0f.png)

My proposition:

1. Change wording "Initial Contribution" to "Initial Deposit" because the word "Deposit" is used in the profile, not contribution. Make it coherent between both pages.

2. The "Total: 0.13" button should be called "Self-fund" and be colored darker to show that it's the default choice.

3. The "Crowdfunding" button should be called "Crowdfund".

4. The field should display a grey "ETH" next to the amount or on the right side to inform the user of the unit of account used

5. When "Self-fund" is activated, a message should say below "I will fund the entire initial deposit myself. This deposit will be reimbursed if my profile is registered and lost if my profile is successfully challenged"

6. When "Crowdfund" is activated, a message should say below "I will not fund the initial deposit or partially fund it and expect other parties to contribute to it. This deposit will be reimbursed if my profile is registered and lost if my profile is successfully challenged"

**Comment by epiqueras** [comment]
Done
