### ISSUE TITLE
Complete the Vouching warning message with explanation about vouching when not yet registered and one vouch at a time

### ISSUE THREAD

**Issue by jragosa** [Proof-Of-Humanity/proof-of-humanity-web#38]
This is the current Vouching warning message:
![image](https://user-images.githubusercontent.com/34345327/107757873-68d66d00-6d26-11eb-97d1-7db441a48dd4.png)

A user might be surprised that when he vouches for X, it will not appear in X's profile because he not registered yet.

We could add a sentence to this Vouching warning message saying that vouching is only counted when you are registered and also explain that you can only vouch for one person at a time.

**Comment by epiqueras** [comment]
Done
