### ISSUE TITLE
Change name of "Vouching" status to make it less confusing

### ISSUE THREAD

**Issue by jragosa** [Proof-Of-Humanity/proof-of-humanity-web#39]
The current naming of the "Vouching" status is confusing and could make users think that profile in "Vouching" means that this profile is currently vouching for other profiles. When the intended meaning is that the profile is waiting to be vouched for.

![image](https://user-images.githubusercontent.com/34345327/107758489-3d07b700-6d27-11eb-85cb-f662b57f5821.png)

Suggestion of clearer naming (by order of preference): 

- "Pending Vouching"
- "Vounching phase"
- "To be vouched for"

**Comment by epiqueras** [comment]
Done
