### ISSUE TITLE
Page loading depends on page skip number

### ISSUE THREAD

**Issue by NandyBa** [Proof-Of-Humanity/proof-of-humanity-web#396]
It's short to request the https://app.proofofhumanity.id/?skip=12 or page with low skip number but the request time for big skip number is insane.

## To Reproduce
Try to go to https://app.proofofhumanity.id/?skip=7224

## Expected Behavior
Same quick page loading with all skip numbers.

**Comment by alcercu** [comment]
Hello! It seems that theGraph only accepts a skip number between 0 and 5000. You can try https://app.proofofhumanity.id/?skip=4992 (which loads instantly) and https://app.proofofhumanity.id/?skip=5004 (which doesn't load at all).

Thanks for the heads up @NandyBa, we will work on improving this!
