### ISSUE TITLE
Sometimes, cards fail to go back in their original positions after losing focus.

### ISSUE THREAD

**Issue by clesaege** [Proof-Of-Humanity/proof-of-humanity-web#4]
![image](https://user-images.githubusercontent.com/8873352/106513483-f619f600-64ca-11eb-8461-26ffe964bd9b.png)

Issue present in both chrome and brave.
On this screenshot, my mouse is focusing on Sam, but Ferit card was stuck in this position.

**Comment by clesaege** [comment]
It seems to happen when the page is losing focus either due to another in browser focus (in my case metamask) or another app getting it (in my case telegram).

**Comment by epiqueras** [comment]
Nice catch. This was hard to replicate.

I fixed it :smile:
