### ISSUE TITLE
"Pending Removal" filter displays both "Pending Removal" and "Challenged Removal" profiles

### ISSUE THREAD

**Issue by jragosa** [Proof-Of-Humanity/proof-of-humanity-web#40]
"Pending Removal" filter displays both "Pending Removal" and "Challenged Removal" profiles. That is not what I would expect as user filtering from pending removal that I want to challenge, I would not want to see those already challenged because I can see those by filtering with "Challenged removal".

![image](https://user-images.githubusercontent.com/34345327/107759370-8278b400-6d28-11eb-82ca-cb94be38396b.png)

Same situation for "Pending registration" filter and "Challenge registration" being displayed

**Comment by epiqueras** [comment]
Done
