### ISSUE TITLE
Twitter Social Icon wrong Href redirect

### ISSUE THREAD

**Issue by Nachobr** [Proof-Of-Humanity/proof-of-humanity-web#402]
**Describe the Bug**
The twitter social icon is pointing to kleros_io twitter, 
**To Reproduce**

**Expected Behavior**
should be redirect to poh twitter 
**Screenshots**
![urltwitterhreftoklerosinsteadpoh](https://user-images.githubusercontent.com/55702500/123222920-cafa6800-d4a6-11eb-924e-85efc64449e5.png)

**Device and Browser Information**
Chrome

**Comment by mtsalenc** [comment]
Solved on 204cfcce37adf2f13998ddb8dd54ea10bac42e4f
