### ISSUE TITLE
Voucher of duplicate is displayed as registered but he is removed

### ISSUE THREAD

**Issue by fnanni-0** [Proof-Of-Humanity/proof-of-humanity-web#408]
**Describe the Bug**
This profile https://app.proofofhumanity.id/profile/0x5cf395b4d5c6bbc44bd26b387f582f10646f76ec was removed, because he vouched a profile which was removed with the Duplicate reason. However, the UI is displaying him as registered.

**To Reproduce**
It should happen the same to this one in a few hours https://app.proofofhumanity.id/profile/0xe30b1c351836ea35d7211734faa2b4c3254435e0.

My guess is that the problem is [here](https://github.com/Proof-Of-Humanity/proof-of-humanity-web/blob/master/subgraph/src/mapping.ts#L317-L343). This callback is probably called AFTER [this](https://github.com/Proof-Of-Humanity/proof-of-humanity-web/blob/5bacc4879693cb8fe58bf4a38de32cd273817f2f/subgraph/src/mapping.ts#L828-L869) other callback is called, but it should be the other way around. The consequence of this is that [this](https://github.com/Proof-Of-Humanity/proof-of-humanity-web/blob/5bacc4879693cb8fe58bf4a38de32cd273817f2f/subgraph/src/mapping.ts#L859) evaluates to false and the following 3 lines never get executed. I haven't implemented nor tested a fix so I don't know for sure.

**Comment by alcercu** [comment]
On it! Thanks.
