### ISSUE TITLE
Submission not showing

### ISSUE THREAD

**Issue by marcwinn76** [Proof-Of-Humanity/proof-of-humanity-web#409]
**Describe the Bug**
My son's profile submission not showing. https://app.proofofhumanity.id/profile/0x4ddc444f614b4DA003D7dF7Bb6DCD36bD4E320d2
This is a previously challenged profile. The ETH has left his wallet but it is still asking him to submit the profile again.
**Device and Browser Information**
Chromebook

**Comment by alcercu** [comment]
Hello! It was a problem with the subgraph not syncing, it's working now. 👍🏻
