### ISSUE TITLE
Empty page when activating a filter from a page with a count superior to the number of pages when that filter is activated

### ISSUE THREAD

**Issue by jragosa** [Proof-Of-Humanity/proof-of-humanity-web#41]
Filter "All" profiles, navigate to the 4th page.

![image](https://user-images.githubusercontent.com/34345327/107759677-eef3b300-6d28-11eb-9beb-1e815d5f3c3e.png)

Then, filter "Registered" profiles, you end up with a blank page

![image](https://user-images.githubusercontent.com/34345327/107759749-0763cd80-6d29-11eb-878f-d93fab679b5b.png)

I would expect to be displayed some "registered" profiles from the last page of "registered profiles even if I am on page with a count superior to the number of pages when activating the filter

**Comment by epiqueras** [comment]
Done
