### ISSUE TITLE
Add Status Progress Flow on profiles

### ISSUE THREAD

**Issue by jragosa** [Proof-Of-Humanity/proof-of-humanity-web#42]
On each profile display a simple status process flow where the current status of the profile is colored and the other statuses greyed out. It would really improve the understanding of the process for users.

@pliniobraga : It could look like this:
![image](https://user-images.githubusercontent.com/34345327/107760725-86a5d100-6d2a-11eb-9850-782f78f9b7e9.png)

**Comment by pliniobraga** [comment]
That's a good idea Jimmy. On Tokens, we use the following statuses flow. I think we could standardize it to reduce the learning curve. 
![Uploading Tokens Fluxogram States.png…]()

**Comment by epiqueras** [comment]
Let's move this to the board since it's not a code issue.

https://github.com/Proof-Of-Humanity/project-management/projects/1
