### ISSUE TITLE
mining pending

### ISSUE THREAD

**Issue by edouardbrasier** [Proof-Of-Humanity/proof-of-humanity-web#421]
Tried to submit my profile with crownfunding=0
the page stays at the mining stage but nothing happens
Used chrome on an android device.
What is the expected behavior?

**Comment by alcercu** [comment]
Hello, it could be that the submission transaction is not mined yet, which gas price did you use? Could you check if your transaction is pending on metamask? Thanks!

**Comment by edouardbrasier** [comment]
I used crowdfunding = 0 which means I should contribute nothing. If this is not allowed (I don't know....) then it should throw an error

**Comment by mtsalenc** [comment]
It's allowed to contribute 0. Do you have the transaction hash? we can help you if you don't know how to find it

**Comment by edouardbrasier** [comment]
I don't know where to find it

**Comment by mtsalenc** [comment]
What wallet are you using? 

If its metamask first click on the transaction (not the buttons, the whole rectangle is a button)

![Screenshot from 2021-07-28 12-33-57](https://user-images.githubusercontent.com/9872474/127308892-d81903e6-17de-49d0-a414-4f8adc3ac989.png)

Then, on the popup, click on the arrow on the top right:

![Screenshot from 2021-07-28 12-34-07](https://user-images.githubusercontent.com/9872474/127308954-5eb59954-ce13-445c-8f61-a75f7798b734.png)

This will open a new browser tab. Copy and paste the URL here

**Comment by edouardbrasier** [comment]
I use metamask wallet on android. There is no transaction in queue.

**Comment by mtsalenc** [comment]
Ok, maybe the transaction was never submitted to begin with. A bit more information:
- Did you use walletconnect?
- What is your address? If you don't want to post it here we can chat privately.

**Comment by edouardbrasier** [comment]
yes I used walletconnect. 
I think when I tried with crownfunding 0.1 it created a transaction but I rejected it. Then when I tried with 0 it never created anything in metamask.
If I use crownfunding = 0 will I have to pay gas fees?
Should I email you my wallet address?

**Comment by edouardbrasier** [comment]
![Screenshot_2021-07-29-09-11-49-958_io metamask](https://user-images.githubusercontent.com/19801998/127448124-6f969854-9bdd-4544-afe4-41b81c5513fd.jpg)
![Screenshot_2021-07-29-09-11-44-462_io metamask](https://user-images.githubusercontent.com/19801998/127448151-5ede36fa-9d50-4b7b-bf85-53a8526be77e.jpg)
 I have tried again and it created a transaction in metamask I was not able to confirm

**Comment by edouardbrasier** [comment]
I have tried again and it created a transaction in metamask. Could you let me know if it worked?
0x404314282751b6ca351afc5298deab2c84317bd02b67473d8503d0ba833d0721

**Comment by mtsalenc** [comment]
Your transaction was mined so yes, it was successful: 
https://app.proofofhumanity.id/profile/0x4587afc318bdcac56bee8b8a78ef662d4eb37fb1

**Comment by mtsalenc** [comment]
Closing this as its not a UI issue.
