### ISSUE TITLE
Lost Fund Submission option

### ISSUE THREAD

**Issue by NingF23** [Proof-Of-Humanity/proof-of-humanity-web#428]
**Describe the Bug**
the Fund Submission button doesn't appear on profiles, only vouching options

**Expected Behavior**
The option should appear for profiles with less than 100% deposit

**Screenshots**
![image](https://user-images.githubusercontent.com/83063111/127323839-a1474dd7-1a3d-4ea4-869d-f042d61b73e4.png)
![image](https://user-images.githubusercontent.com/83063111/127323662-bb6c8142-7085-40ae-bfeb-5c85b7ca2c87.png)
![image](https://user-images.githubusercontent.com/83063111/127323688-fae70ed8-86af-40c9-938f-5a071d44341a.png)

**Device and Browser Information**
All browsers

**Comment by sepu85** [comment]
hi! just commenting here to be updated about the evolution of this fix...
