### ISSUE TITLE
Add a "Tweet" button on "My profile" page

### ISSUE THREAD

**Issue by jragosa** [Proof-Of-Humanity/proof-of-humanity-web#43]
Add a "Tweet button" on "My profile" page like there is in the appeal section of profiles challenged.

This "Tweet" button would pop-up a tweet with "Register and vouch for me on Proof of Humanity: URL" if you're in "Pending Vouching status or "Check out my profile on Proof of Humanity : URL" if you're in other statuses.

**Comment by epiqueras** [comment]
Done
