### ISSUE TITLE
Appeal tab not showing

### ISSUE THREAD

**Issue by fnanni-0** [Proof-Of-Humanity/proof-of-humanity-web#431]
In this profile https://app.proofofhumanity.id/profile/0x75b885aDb09823bfb1ef8227f5943801EA9853C2 the appeal period is ongoing, but the appeal tab is not showing.

I think the problem is in the subgraph. Rounds info is not correctly handled when a challenge is requested and [this](https://github.com/Proof-Of-Humanity/proof-of-humanity-web/blob/979b4fa1440850f29897d5b28c810e31f45fda0c/_pages/profile/%5Bid%5D/submission-details-accordion.js#L91) line in the UI seems to evaluate to `false`, but it should evaluate to `true`.

The first time a request is challenged, there is no need to initialize round 0, because it was already done during the [profile submission](https://github.com/Proof-Of-Humanity/proof-of-humanity-web/blob/979b4fa1440850f29897d5b28c810e31f45fda0c/subgraph/src/mapping.ts#L235-L246), right? However, for further challenges of the same request, round 0 needs to be initialized. And for all challenges, round 1 has to be initialized as well, the same way the next round is initialized when both sides of an appeal [get fully funded](https://github.com/Proof-Of-Humanity/proof-of-humanity-web/blob/979b4fa1440850f29897d5b28c810e31f45fda0c/subgraph/src/mapping.ts#L1026-L1053).

**Comment by alcercu** [comment]
On it! 👍🏻 I am syncing a test version which should solve it.
