### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by corbt** [Proof-Of-Humanity/proof-of-humanity-web#445]
Hey, I'm looking at implementing [some improvements](https://gov.proofofhumanity.id/t/fixing-low-hanging-fruit-ux-issues-in-the-poh-frontend-app/1057) to the PoH frontend, but I noticed this repository is listed as UNLICENSED. I'm not sure what what means in practice—does the existing codebase belong to Kleros? The individuals who pushed the code? The PoH DAO (I don't think that's possible, because it's not a legal entity)?

 cc @clesaege

**Comment by clesaege** [comment]
It's created by Kleros Cooperative thus in MIT license.
