### ISSUE TITLE
Add a message about notification subscription when/after submitting profile

### ISSUE THREAD

**Issue by jragosa** [Proof-Of-Humanity/proof-of-humanity-web#45]
Users (who won't be used to Kleros products) need to know that they have to subscribe to email notifications to be warned of any challenge against them.

I suggest adding a message either on the "Submit profile" page (or as a modal after submission) that says:

"Remember to subscribe to email notifications in "Account>Notifications" to be warned about your profile status changes and any potential challenge raised against your registration."

**Comment by epiqueras** [comment]
Done
