### ISSUE TITLE
Batch sent but transaction never arrived to contract!

### ISSUE THREAD

**Issue by joaquinvismarax** [Proof-Of-Humanity/proof-of-humanity-web#454]
Hi guys, i sent the Batch, it says ( Although one or more Error Occurred [Reverted] Contract Execution Completed), but i do not see the transaction on the contract (0x82458d1C812D7c930Bb3229c9e159cbabD9AA8Cb). 
HELP !

**Screenshots**
![image](https://user-images.githubusercontent.com/93714836/140312010-cc1463ad-46bc-4527-9351-df8c95080a8c.png)

**Comment by eccentricexit** [comment]
Would you mind posting that transaction hash?

**Comment by joaquinvismarax** [comment]
Yes ! Sorry 0xfbb0d965735d39551456fe85bef2767c667fc104c73cefda5410010f55ac0a6a

**Comment by eccentricexit** [comment]
Looks like the challenge period ended 2 hours ago, but the transaction was mined 6 hours ago (before the challenge period ended).

How did you submit the tx? Just clicked the button in the UI?

**Comment by joaquinvismarax** [comment]
![image](https://user-images.githubusercontent.com/93714836/140316209-de4316db-ab5b-423d-af64-8cad6fa320f5.png)

Hey Matt ! For me challenge period ended 6 ago, and as soon as it finished, i clicked the Finalize registrarion and start acruiing!

**Comment by eccentricexit** [comment]
Moved this to 455 and added cause of the issue. 

Do you have a telegram joaquinvismarax?

**Comment by joaquinvismarax** [comment]
Yes ! 541134784748

**Comment by eccentricexit** [comment]
Deleted contact to preserve privacy.
