### ISSUE TITLE
Crowdfunding information still shown in UI after case resolved

### ISSUE THREAD

**Issue by whwgeorge** [Proof-Of-Humanity/proof-of-humanity-web#46]
**Describe the Bug**

The profiles of https://proof-of-humanity.netlify.app/profile/0x0b6b4566f9ac32e06c309bcbbd906a380237cb1e?network=kovan and https://proof-of-humanity.netlify.app/profile/0x0d256c49e5df2b9bae2a04b6c2622ac459396dc2?network=kovan which correspond to Kovan court cases 805 and 806 respectively still show information about crowdfunding under the appeal tab, particularly with the text "Previous round is still in progress." However, these cases are resolved on the Kovan court and the statuses of the profiles on PoH have been correctly modified according to the court rulings (to Registered (Expired) and Removed accordingly). 

**To Reproduce**

**Expected Behavior**

**Screenshots**

![crowdfundingpresentafterresolved](https://user-images.githubusercontent.com/32513740/107810702-16ec1200-6d3b-11eb-8c54-1290fd2ae7fd.png)

**Device and Browser Information**

**Comment by epiqueras** [comment]
Fixed

Nice catch.

It was an issue with handling refuse to arbitrate in the first round.
