### ISSUE TITLE
Vouch bug

### ISSUE THREAD

**Issue by L3ml** [Proof-Of-Humanity/proof-of-humanity-web#462]
Hi, sorry for my translation, but in this decentralized world you have to use only one language.
I have had my vouch blocked for more than 7 months, the first profile that I endorsed received a challenge (352pixel) and since then I can't give vouch to anyone else. The challenged profile uploaded it again and it is already registered, but after that my vouch remained blocked.
I don't see the option to remove it either, as explained on the page. 
"Can I remove a vouch?
Yes, you can remove a vouch at anytime by going to the vouched profile and clicking on "Remove Vouch".
Please tell me what information you need to verify my case.
Thank you

Translated with www.DeepL.com/Translator (free version)

**Comment by fnanni-0** [comment]
Hi, can you provide your profile address so that I can check what happened?

**Comment by L3ml** [comment]
https://app.proofofhumanity.id/profile/0xA770d7d1E99d1e4510aFFc670BC983fbcDC819F5

**Comment by fnanni-0** [comment]
We are working on a fix. It should be solved soon. Thanks for reporting.

**Comment by fnanni-0** [comment]
@L3ml This should be solved now.

**Comment by L3ml** [comment]
Thanks, I will try if it works
