### ISSUE TITLE
Profile not advancing through Vouching Phase

### ISSUE THREAD

**Issue by gianpetrii** [Proof-Of-Humanity/proof-of-humanity-web#464]
**Describe the Bug**
I have been vouched twice more than 4 days ago and still haven´t gonne through to the next phase
My profile: [https://app.proofofhumanity.id/profile/0x3976CA473cc683EfEE877ca3d7E5f39452C62A0E](url)

**Expected Behavior**
Go to the next pahse
**Screenshots**
![image](https://user-images.githubusercontent.com/55300986/142294652-137bfb66-b875-4c7f-9b4c-3796f0298bbc.png)

**Device and Browser Information**
I used Chrome with Methamask extension, on Windows 10, although I dont think my browser info has anything to do with the problem, feels like its more of an internal issue

**Comment by fnanni-0** [comment]
Your profile moved to Pending Registration a few hours ago. Probably the vouches were being used on other profiles or it simply took a while for your profile to move to the next phase.
