### ISSUE TITLE
Only one link to the farming site which would display both pools

### ISSUE THREAD

**Issue by clesaege** [Proof-Of-Humanity/proof-of-humanity-web#48]
![image](https://user-images.githubusercontent.com/8873352/107985751-98090a80-6fc2-11eb-9c35-6e5ecb6152d7.png)

Pool display example 
![image](https://user-images.githubusercontent.com/8873352/107985484-10bb9700-6fc2-11eb-84c0-2c153a686dab.png)

**Comment by epiqueras** [comment]
Fixed
