### ISSUE TITLE
Tooltip

### ISSUE THREAD

**Issue by federicoast** [Proof-Of-Humanity/proof-of-humanity-web#49]
Nothing happens when I place the mouse over the tooltip.

<img width="644" alt="Captura de pantalla 2021-02-15 161936" src="https://user-images.githubusercontent.com/16290963/107985879-bdd5e580-6fa9-11eb-8d0a-ca3088843967.png">

**Comment by epiqueras** [comment]
It's not a tooltip. It's where the UBI logo would go if the contract had one.
