### ISSUE TITLE
My ETH disappeared when I registered

### ISSUE THREAD

**Issue by jucavica** [Proof-Of-Humanity/proof-of-humanity-web#494]
I need help. my ETH disappeared, I lost my money, please help. My portfolio is 0xFfd5bD2adc06c0ca0bA7cF0104F51fD842fEDbf9

**Comment by jucavica** [comment]
Mi registro no aparece y mi dinero desapareció, necesito ayuda, esta es mi cartera 0xFfd5bD2adc06c0ca0bA7cF0104F51fd842fedbf9

**Comment by aahna-ashina** [comment]
@jucavica Your Ethereum account is empty: https://etherscan.io/address/0xFfd5bD2adc06c0ca0bA7cF0104F51fD842fEDbf9

**Comment by jucavica** [comment]
Yes, my account is totally empty, I lost all my family's money, I had
almost $ 600 in ETH.  The transaction was executed with Metamask and I lost
everything, I ask you to please help me, I am from Venezuela and I have no
money

**Comment by jucavica** [comment]
Please I need help.  I need to get my $ 600 back.  My wallet is
0xFfd5bD2adc06c0ca0bA7cF0104F51fD842fEDbf9 Please help me

**Comment by aahna-ashina** [comment]
@jucavica It looks like you sent the money to the wrong blockchain. There is money on the _Binance Smart Chain_ (`BEP20`): https://www.bscscan.com/address/0xFfd5bD2adc06c0ca0bA7cF0104F51fD842fEDbf9

In order to use Proof of Humanity, you need to send the money to the Ethereum blockchain instead (`ERC-20`).

**Comment by aahna-ashina** [comment]
@alcercu This issue can be closed.

**Comment by jucavica** [comment]
I had the money in the Binance chain and I passed it to my ETH portfolio in
my Metamask, once I had the ETH in my Metamask I filled out the
registration with the photo and video and I selected the option to finance
the 0.128 ETH, I did not want to pay it, I wanted to be paid, when I
clicked the send button my Metamask opened, I signed and took all my ETH

**Comment by jucavica** [comment]
Please do not close this case, I need to get my money back, it is my
family's capital

**Comment by jucavica** [comment]
If you can't give me my money back, at least include me in the project
humanityproof.  I am from Venezuela and the economic situation is very
difficult

**Comment by alcercu** [comment]
hey @jucavica as @aahna-ashina pointed out, your money is on BSC, you can't see it because to interact with Proof of Humanity you switched chain on your wallet.
