### ISSUE TITLE
No me deja crear mi cuenta el botón entregar no funciona, ayudenme

### ISSUE THREAD

**Issue by JorgeLPM2** [Proof-Of-Humanity/proof-of-humanity-web#495]
**Describe the Bug**

**To Reproduce**

**Expected Behavior**

**Screenshots**

**Device and Browser Information**
Chrome. Motorola Moto G Stylus 2020. Android 11

**Comment by aahna-ashina** [comment]
Chrome on Android does not support Web3. So you will have to install an app that has a built-in Web3 browser.

Here are some apps you could try:

- MetaMask
- MyEtherWallet
- Status

**Comment by aahna-ashina** [comment]
@alcercu This issue can be closed.
