### ISSUE TITLE
Outdated tutorial rules

### ISSUE THREAD

**Issue by L3ml** [Proof-Of-Humanity/proof-of-humanity-web#496]
The rules that appear in the tutorial are not the same as those that appear in the disputes, it should be updated.

![photo_2021-12-30_11-19-25](https://user-images.githubusercontent.com/94531182/147760018-5b9172b9-03d6-4764-a9f0-1eb438577c9c.jpg)

**Comment by aahna-ashina** [comment]
@L3ml Are you referring to the "Tutorial" link in the drop-down menu?

<img width="280" alt="Screen Shot 2021-12-31 at 1 17 36 AM" src="https://user-images.githubusercontent.com/95955389/147788573-6bf2d73b-749d-4de1-8291-1b4e1c26c023.png">

**Comment by L3ml** [comment]
hello, please check the link attachment, with the disputes attachment.

![Captura de pantalla 2021-12-30 210137](https://user-images.githubusercontent.com/94531182/147795346-932bfe9f-d520-42d4-83af-3194aa1a1a13.png)


![Captura de pantalla 2021-12-30 205438](https://user-images.githubusercontent.com/94531182/147795225-d39f0d3f-368a-42e3-8694-fa41fea73070.png)

**Comment by aahna-ashina** [comment]
@alcercu Is there a GitHub repository where we can edit this GitBook page?

https://kleros.gitbook.io/docs/products/proof-of-humanity/proof-of-humanity-tutorial

**Comment by L3ml** [comment]
yes, you could try to download the file? so you can corroborate what I'm saying

**Comment by L3ml** [comment]
sorry for my english, this using a translator

**Comment by alcercu** [comment]
The repository for the gitbook is https://github.com/kleros/kleros-docs @aahna-ashina I created a PR to update the tutorial. Thanks for the heads up! 👏🏻
