### ISSUE TITLE
Video not playing on web app, but playable when downloaded

### ISSUE THREAD

**Issue by cvidan** [Proof-Of-Humanity/proof-of-humanity-web#499]
**Describe the Bug**
Video not playing on web app, but playable when downloaded

**To Reproduce**
1. Go to https://app.proofofhumanity.id/profile/0x66da93165a901716C6b25D9B7F09c7fEAe245A2E
2. "No video with supported format and MIME type found"
3. Go to https://ipfs.kleros.io/ipfs/QmNv9yMHfL7g38RaeinUXaxrATx2dsXyV7ZKaThuBd2KcF/video.webm
4. Download video (ctrl + s)
5. Video is playable (with VLC, etc)

**Expected Behavior**
Video should be playable from app.proofofhumanity.id

**Screenshots**
![image](https://user-images.githubusercontent.com/25379877/147900077-1b972646-bef3-4d52-b221-a41a7a1e9d70.png)

**Device and Browser Information**
Windows/Firefox

**Comment by aahna-ashina** [comment]
@cvidan Which browser are you using?

**Comment by aahna-ashina** [comment]
@alcercu Any suggestions on how to solve this problem?

**Comment by alcercu** [comment]
It's playing for me on Chrome, but not on Firefox, I will take a look 👍🏻

**Comment by alcercu** [comment]
Looks like it's a Firefox problem, no clear solution other than changing browser 🤔 I found older posts on the forums and they were solved after a couple of releases (last message in [this](https://support.mozilla.org/en-US/questions/1048378#question-reply) thread).
