### ISSUE TITLE
Requested removals for three profiles and filtered search for 'pending removal' but the page just loads 

### ISSUE THREAD

**Issue by btcethph** [Proof-Of-Humanity/proof-of-humanity-web#5]
![filtering](https://user-images.githubusercontent.com/63893001/106580035-66348480-657c-11eb-86e8-4c903133a3f1.jpg)

Tried the filtering three times; used Brave browser

**Comment by epiqueras** [comment]
This is caused by the same issue as #3. When that is fixed, this should be too. In the meantime, you can try refreshing.
