### ISSUE TITLE
ETH logo

### ISSUE THREAD

**Issue by federicoast** [Proof-Of-Humanity/proof-of-humanity-web#50]
Not sure there should be an ETH logo there? The DAI pool doesn't have the logo.

<img width="677" alt="Eth logo" src="https://user-images.githubusercontent.com/16290963/107986050-068d9e80-6faa-11eb-81c4-63b1700584fc.png">

**Comment by epiqueras** [comment]
Yeah the Kovan DAI doesn't have a logo.
