### ISSUE TITLE
Two transactions when trying to submit application

### ISSUE THREAD

**Issue by discotekk** [Proof-Of-Humanity/proof-of-humanity-web#502]
**When trying to submit application, metamask launches for payment and two transactions appear (they look exactly the same) EX: if i reject the first one, i have another similar transaction which i can either accept or reject**

**To Reproduce**

**Only one transaction should appear?**

![tempsnip](https://user-images.githubusercontent.com/97722892/149461650-15cb933b-f809-422a-bb14-d53131a1225a.png)

**Metamask for Mozilla Firefox on a Desktop Windows Computer**

**Comment by michaelsproul** [comment]
This is related to https://github.com/Proof-Of-Humanity/proof-of-humanity-web/issues/308

**Comment by bilinkis** [comment]
Issue still happening. Seems to be isolated to Mozilla Firefox browser. 
That was the only browser in which I could replicate the bug (Chrome and Edge working properly). 
@alcercu
