### ISSUE TITLE
No option to remove near expiry profiles

### ISSUE THREAD

**Issue by NingF23** [Proof-Of-Humanity/proof-of-humanity-web#504]
**Describe the Bug**
Unable to remove near expiry profiles due to the option not being available

**Expected Behavior**
Request to remove should appear on a profile no matter how long it's registered

**Screenshots**
![image](https://user-images.githubusercontent.com/83063111/149834717-efbcf49a-c8d1-447f-b819-9d6ab7e23529.png)
![image](https://user-images.githubusercontent.com/83063111/149834768-18fc7aca-2d7e-42f4-8193-8538a0a833e2.png)
![image](https://user-images.githubusercontent.com/83063111/149834842-461ed65a-768e-485f-8e9f-36013bad3c37.png)
![image](https://user-images.githubusercontent.com/83063111/149834797-b7212b3e-4b22-45d6-a237-1c4e28827bb3.png)

**Device and Browser Information**
Brave, Chrome, Edge, Firefox

**Comment by fnanni-0** [comment]
This is the expected behavior. It's not allowed to request a removal while profiles are in the renewal period.
