### ISSUE TITLE
Allow to review one's video

### ISSUE THREAD

**Issue by clesaege** [Proof-Of-Humanity/proof-of-humanity-web#51]
![image](https://user-images.githubusercontent.com/8873352/107986094-41500080-6fc3-11eb-96ab-b7d895ccb0bb.png)
No need to automatically play the video in mute. But allow clicking the video to play it in large screen with sound.

**Comment by epiqueras** [comment]
Fixed

**Comment by clesaege** [comment]
It doesn't work for me 
![image](https://user-images.githubusercontent.com/8873352/107993832-516fdc00-6fd3-11eb-9d7e-489d337391c7.png)

**Comment by clesaege** [comment]
Moreover there is some weird cursor down and three points instead of the play icon.

**Comment by epiqueras** [comment]
Fixed. It was too small and the drop handler was restarting the video on click.
