### ISSUE TITLE
Withdraw Submission isn't refunding the same amount of ETH sent in Add Submission

### ISSUE THREAD

**Issue by carfloresf** [Proof-Of-Humanity/proof-of-humanity-web#526]
**Describe the Bug**
I sent 0.175 ETH in Add Submission transaction: https://etherscan.io/tx/0x93e524b47899c9abe12a1ab79a75a77f9d26e27c19749c3b09f660c603f58dc0

A day and a few hours later I Withdrew my submission pressing the button withdraw and executing: Withdraw Submission:
https://etherscan.io/tx/0x93e524b47899c9abe12a1ab79a75a77f9d26e27c19749c3b09f660c603f58dc0

But only received 0.125 ETH back.

**To Reproduce**
1.- Add new Submission: adding photo, video, asked ETH amount was 0.175 plus gas.
2.- Accept transaction on metamask
3.- Withdraw Submission paying gas fees.
4.- Accept transaction on metamask

**Expected Behavior**
1.- Receive full deposit amount back

**Screenshots**
![image](https://user-images.githubusercontent.com/8068617/158946971-a8eef123-8b1e-4b20-b840-9daaf79a8506.png)
![image](https://user-images.githubusercontent.com/8068617/158947007-7e3599ab-7d4e-4b34-b592-4c8c936d4b71.png)

**Device and Browser Information**
- Chrome Version 99.0.4844.74 with Metamask
- Windows 11 Pro, 5950X, 32GB Ram, RTX 3080

**Comment by bilinkis** [comment]
Hello Carlos. As you can see in the first screenshot you provided, the other 0.05ETH came back when the Add Submission was confirmed as an internal transaction.

**Comment by carfloresf** [comment]
Yeah, just noticed that, thank you!
