### ISSUE TITLE
Gas fees excesivos luego de vouching phase (advance to pending)

### ISSUE THREAD

**Issue by hgreco85** [Proof-Of-Humanity/proof-of-humanity-web#530]
**Describe the Bug**
Mi perfil está en "Vouching Phase", ya tengo 1/1 en vouchers y el perfil quedó con el mensaje "Wait or Advance to Pending" pero llevo esperando una semana y no avanza solo... y cuando hago click en "Advance to Pending", el gas requerido supera 1 ETH. 
Pensé que podía ser algo temporal, pero pasan los días y los valores de gas varían pero siempre superan 1 ETH y me parece excesivo.

**To Reproduce**
https://app.proofofhumanity.id/profile/0x0a837579d704cab93d4880edd35b1f37c62c09c6

**Expected Behavior**
 
**Screenshots**
![image](https://user-images.githubusercontent.com/104028160/164071331-71050b2c-ca52-476e-aebd-5b11545d123a.png)
![image](https://user-images.githubusercontent.com/104028160/164071476-cde31011-97f2-4444-a5a9-836f939a9757.png)

**Device and Browser Information**

**Comment by bilinkis** [comment]
@alcercu there was probably a problem with the vouches signature. I gave him a new vouch to help the profile advance, but there was an underlying issue that I didn't solve.
