### ISSUE TITLE
Deposit

### ISSUE THREAD

**Issue by federicoast** [Proof-Of-Humanity/proof-of-humanity-web#54]
- The word "Deposit" seems smaller than "Evidence Name". They should be the same size/font.

- Remove the word "Deposit" after ETH.

- "Max size: 2mb" should be centered. 

<img width="650" alt="Deposit" src="https://user-images.githubusercontent.com/16290963/107986545-1194fe80-6fab-11eb-883f-cab656cee819.png">

**Comment by epiqueras** [comment]
Fixed
