### ISSUE TITLE
It takes 2 minutes for changes in the 'profile status' to take effect and needs manual browser refresh

### ISSUE THREAD

**Issue by btcethph** [Proof-Of-Humanity/proof-of-humanity-web#6]
Same results for actions done below:

1.  Removal request
2. Challenge removal

The lag makes it look like nothing is happening after the transaction is confirmed

**Comment by epiqueras** [comment]
This is because the subgraph takes a while to update. @pliniobraga, what do you think we should do here.

**Comment by epiqueras** [comment]
Fixed
