### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by federicoast** [Proof-Of-Humanity/proof-of-humanity-web#62]
It doesn't let me go to 0.09.

I can only increase the contribution by natural numbers: 1, 2, 3... not decimals.

<img width="551" alt="Contribution 2" src="https://user-images.githubusercontent.com/16290963/107988244-53737400-6fae-11eb-84f9-4256a03b5ac6.png">

**Comment by epiqueras** [comment]
Fixed
