### ISSUE TITLE
Update initial deposit

### ISSUE THREAD

**Issue by clesaege** [Proof-Of-Humanity/proof-of-humanity-web#64]
![image](https://user-images.githubusercontent.com/8873352/107993583-aced9a00-6fd2-11eb-8dc9-8a8988d58c11.png)
Have the button in the same style as the "Crowdfund" button. Have it preselected. Don't show the number field if "Self Fund" is selected.

**Comment by epiqueras** [comment]
It was an issue with your locale using a comma there. Fixed.
