### ISSUE TITLE
Add the link to the POH website on footer' left side.

### ISSUE THREAD

**Issue by pliniobraga** [Proof-Of-Humanity/proof-of-humanity-web#66]
Link to POH website for more information on footer: 
![footer-link-to-webpage](https://user-images.githubusercontent.com/15757255/108110937-c47c5f80-7072-11eb-8e99-4ab3907ae503.png)

**Comment by Meibols** [comment]
Hi Plinio, how can I edit my profile pic?? Thanks

**Comment by epiqueras** [comment]
Done
