### ISSUE TITLE
Profile pic edition

### ISSUE THREAD

**Issue by Meibols** [Proof-Of-Humanity/proof-of-humanity-web#67]
**Is your feature request related to a problem?**
Is impossible to discover how to change or edit the profile picture
**Describe the solution you'd like.**
An interface more clear would be necesary
**Describe alternatives you've considered.**
Insert a button of edit or change

**Comment by epiqueras** [comment]
Editing is not permitted. It would defeat the purpose of peer verification.

You can only change things when renewing or reapplying.

**Comment by Meibols** [comment]
why Clement o Ronald were able to do it?

**Comment by epiqueras** [comment]
No one is able to. What makes you think they did?

**Comment by Meibols** [comment]
I would like to put my personal picture as Clement or Ronald...
![Profile pics](https://user-images.githubusercontent.com/36730604/108164920-fbde2100-70f1-11eb-947d-0c809d1eeee0.jpg)

**Comment by Meibols** [comment]
can I challenge myself? I have done it and it makes little sense to me that one can challenge oneself.

**Comment by epiqueras** [comment]
They didn't edit their picture. They applied with that. You didn't apply; I added you manually so that you could test things, and that is the stock image I copied from another profile.

>can I challenge myself? I have done it and it makes little sense to me that one can challenge oneself.

You might want to remove your profile to reapply instead of waiting for it to expire if you lost your key, for example.

**Comment by Meibols** [comment]
Ok, thanks Enrique...
