### ISSUE TITLE
Update the POH website to the latest iterations. Check the design.

### ISSUE THREAD

**Issue by pliniobraga** [Proof-Of-Humanity/proof-of-humanity-web#69]
Update the POH website to the latest iterations.  
-Update the top section to white background and lighter avatar images.
-Include the play button to open the video explainer.
-Include the Pools link on the top navbar which scrolls to the Pools section of the page when clicked.
-Update the button (Share POH with the World) in the bottom section to yellow like the other buttons.
-No texts below section titles: (Unlocking new possibilities) and (Your digital identity).
-POH comparison chart on the right, after social graph analysis.

Check the design:
![POH Landing Page](https://user-images.githubusercontent.com/15757255/108214641-27bbcf80-710f-11eb-9fe2-f5309c6db056.png)

**Comment by epiqueras** [comment]
Done
