### ISSUE TITLE
reword description when challenging a request

### ISSUE THREAD

**Issue by btcethph** [Proof-Of-Humanity/proof-of-humanity-web#7]
![challenge description](https://user-images.githubusercontent.com/63893001/106584704-79961e80-6581-11eb-9408-bbb2121669b2.jpg)

Since there's no text box allotted for a requester to remove a certain profile, can the 'title' and 'description' in doing so be reworded differently?

suggestion:
Error >> Remove profile 
Description >> The profile is not a real person / is a duplicate

**Comment by epiqueras** [comment]
<img width="1067" alt="Screen Shot 2021-02-02 at 9 00 53 AM" src="https://user-images.githubusercontent.com/19157096/106634976-29916a80-6535-11eb-8cf1-29b8c66778c2.png">

I've added the form for it and made it required so that this doesn't happen.
