### ISSUE TITLE
Missing the icon from the original design.

### ISSUE THREAD

**Issue by pliniobraga** [Proof-Of-Humanity/proof-of-humanity-web#70]
Missing the icon from the original design.
![Screen Shot 2021-02-17 at 11 12 49](https://user-images.githubusercontent.com/15757255/108216433-3acf9f00-7111-11eb-8864-13db34463ec0.png)

**Comment by epiqueras** [comment]
@clesaege @pliniobraga Don't you think it feels redundant so close to the logo on the top left?

**Comment by epiqueras** [comment]
Done
