### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by Meibols** [Proof-Of-Humanity/proof-of-humanity-web#72]
When I save my mail to receive notifications there is no visual communication that the mail is saved. Is a little bit confuse cause I´m not sure is registered.
![mail saved](https://user-images.githubusercontent.com/36730604/108315318-876fb480-71bb-11eb-825f-1087a6707d49.jpg)

**Comment by epiqueras** [comment]
Added a message.

**Comment by Meibols** [comment]
Thanks!
