### ISSUE TITLE
Primary Document

### ISSUE THREAD

**Issue by federicoast** [Proof-Of-Humanity/proof-of-humanity-web#76]
"Primary Document" is a very specific Kleros word and new people will not understand it. A newcomer will probably think this is a requirement to submit your ID or passport. I think we want to explain what this is. I'd probably clarify here something like "Submission Guidelines".

Also, when I click into "Primary Document" nothing happens. I should be able to download the document, right? Maybe adding a little PDF icon would make it clearer too.

<img width="884" alt="Captura de pantalla 2021-02-19 093930" src="https://user-images.githubusercontent.com/16290963/108505694-8eb7c080-7296-11eb-960a-6e9382934040.png">

**Comment by epiqueras** [comment]
The link is not going anywhere because the current meta evidence has no primary document.

I'm not sure what the correct wording is, but this isn't a bug.
