### ISSUE TITLE
Submission Confirmation

### ISSUE THREAD

**Issue by federicoast** [Proof-Of-Humanity/proof-of-humanity-web#77]
I made a submission of a profile under the name of David Hume and chose the crowdfunding mechanism.

When the submission is done, you don't get a "success" message telling you "Congratulations, your profile was submitted and is now in the vouching stage."

It would be good to have some "feedback message". Otherwise, the user might stay thinking whether the submission was done or not (ultimately, I had to confirm it was done in the homepage of the Dapp).

![Uploading Captura de pantalla 2021-02-19 094737.png…]()

**Comment by epiqueras** [comment]
The page should now refresh and show you your new profile.
