### ISSUE TITLE
Submission Contribution

### ISSUE THREAD

**Issue by federicoast** [Proof-Of-Humanity/proof-of-humanity-web#78]
There seems to be an image behind the red cross. Something doesn't look good there.

<img width="468" alt="Captura de pantalla 2021-02-19 100217" src="https://user-images.githubusercontent.com/16290963/108507844-ae9cb380-7299-11eb-8052-b07a581279c5.png">

**Comment by epiqueras** [comment]
That's either a browser extension or the native input's arrows.
