### ISSUE TITLE
Contribution Comma/Point Problem

### ISSUE THREAD

**Issue by federicoast** [Proof-Of-Humanity/proof-of-humanity-web#79]
I had already reported this bug but it seems it isn't fixed.

In the contribution screen, when I type 0.08 it doesn't accept it. The point doesn't even show up.

I have to type in 0,08 (with a comma) in order to work.

<img width="479" alt="Captura de pantalla 2021-02-19 100821" src="https://user-images.githubusercontent.com/16290963/108508356-70ec5a80-729a-11eb-81bd-c99b43dd4b7b.png">

**Comment by epiqueras** [comment]
It should be good now. If not, please add which browser and keyboard I can reproduce this with.
