### ISSUE TITLE
"Account" button inactive (needs double click to work)

### ISSUE THREAD

**Issue by PresenceNumerique** [Proof-Of-Humanity/proof-of-humanity-web#8]
When clicking on the "Account" button on the landing page, nothing happens.
No popup window proposing to connect a wallet.

** Expectated behaviour **
Propose to connect a wallet then allow to access to account infos/settings (I suppose but at least an info message should tell what is expected).
Note that if I click on another button on someone's profile (like 'Seize UBI") it does propose me to connect my wallet.

![image](https://user-images.githubusercontent.com/46331204/107129987-d9662f80-68c9-11eb-8f34-fdb9a2c533bb.png)

**Device and Browser Information**
Using Brave browser v1.19.90 with metamask connected to Kovan network.

**Comment by PresenceNumerique** [comment]
Ok, just noticed that when I double click the "Account" button it does bring a small window that allows me to connect.

If it's what is expected it's not intuitive.

**Comment by PresenceNumerique** [comment]
I tested some other buttons:
"Submit Evidence": requires 3x clicks for the window to pop.
"Removal request": requires 2x clicks for the window to pop.

**Comment by epiqueras** [comment]
https://user-images.githubusercontent.com/19157096/107137016-2b548880-68bd-11eb-8f8f-25d7196500aa.mov

All buttons work as expected on my machines.

Can you try another browser to see if that's the issue? Multiple clicks solving it makes me think your mouse might be broken, or you might have some accessibility feature turned on.

**Comment by PresenceNumerique** [comment]
I tried on Firefox/Edge/Brave on 2 different computers (with 2 different mouses) and I still have to double click.
I have no accessibility feature activated that I would be aware of.

I do not have any such clicking issue on other apps.

**Comment by epiqueras** [comment]
Have you tried Chrome?

**Comment by PresenceNumerique** [comment]
Just did try with chrome and it works well with one click.

**Comment by epiqueras** [comment]
Fixed.

It was a CSS issue with the popups on specific browser versions.
