### ISSUE TITLE
There's no button to resubmit an expired profile. 

### ISSUE THREAD

**Issue by pliniobraga** [Proof-Of-Humanity/proof-of-humanity-web#80]
**Describe the Bug**
I'm using 2 addresses to test, and both have expired. I can't find a button to resubmit the profile then continue testing.

**Expected Behavior**
Having a (Resubmit Button) on Settings to be able to start again using the same addresses. It seems I'm locked in an expired profile and nothing can be done. There's no message explaining if it will be possible to resubmit at some point or not. (Not sure if it's just a limitation of the Testnet, though, in this case just ignore this.)

**Comment by epiqueras** [comment]
Fixed

It wasn't accounting for the new expired status.
