### ISSUE TITLE
Removing the blue border stroke from clicked components.

### ISSUE THREAD

**Issue by pliniobraga** [Proof-Of-Humanity/proof-of-humanity-web#81]
We can remove the blue border stroke from clicked/focused components:
![Screen Shot 2021-02-19 at 10 51 57](https://user-images.githubusercontent.com/15757255/108518241-1ad1e400-72a7-11eb-9d3c-cd8c0c4470a7.png)
![Screen Shot 2021-02-19 at 10 43 45](https://user-images.githubusercontent.com/15757255/108518245-1c9ba780-72a7-11eb-8999-fe9733d168fd.png)

**Comment by epiqueras** [comment]
You can't remove focused styles. It's against a11y standards.
