### ISSUE TITLE
The checkbox is not aligned on Account > Notifications

### ISSUE THREAD

**Issue by pliniobraga** [Proof-Of-Humanity/proof-of-humanity-web#82]
The checkbox is not aligned on Account > Notifications. The text should be next to the checkbox.
![Screen Shot 2021-02-19 at 10 48 48](https://user-images.githubusercontent.com/15757255/108518698-9af84980-72a7-11eb-8cd6-0785adf1c4bf.png)

**Comment by epiqueras** [comment]
Done
