### ISSUE TITLE
The top background is still yellowish. 

### ISSUE THREAD

**Issue by pliniobraga** [Proof-Of-Humanity/proof-of-humanity-web#83]
The top background is still yellowish when I open it on my device. It should be full white #FFFFFF, as the design.

How I currently see it:
![Screen Shot 2021-02-19 at 10 44 20](https://user-images.githubusercontent.com/15757255/108519289-42757c00-72a8-11eb-9ee2-d6c7807666c2.png)

The design:
![Screen Shot 2021-02-19 at 11 48 22](https://user-images.githubusercontent.com/15757255/108519494-70f35700-72a8-11eb-9e5b-d7d6c230a4f0.png)

**Comment by epiqueras** [comment]
Done
