### ISSUE TITLE
Pool Icons

### ISSUE THREAD

**Issue by federicoast** [Proof-Of-Humanity/proof-of-humanity-web#84]
These icons are too close to each other.

Also, what's the text that should appear when you place your mouse over the QUESTION MARK icon?

<img width="614" alt="Captura de pantalla 2021-02-19 120630" src="https://user-images.githubusercontent.com/16290963/108522020-19a2b600-72ab-11eb-8854-9b74c8ce114c.png">

**Comment by epiqueras** [comment]
It's the token pair, but the UBI coin doesn't have a logo yet on Uniswap. This is just the Uniswap UI.
