### ISSUE TITLE
The Appeal module should be hidden after both sides fully fund it.

### ISSUE THREAD

**Issue by pliniobraga** [Proof-Of-Humanity/proof-of-humanity-web#85]
The Appeal module should be hidden after both sides fully fund it. There's no need to display it once a new round starts, as there's no action allowed until the jurors' decision is made. 

![Screen Shot 2021-02-19 at 11 58 04](https://user-images.githubusercontent.com/15757255/108524922-4efcd300-72ae-11eb-8da2-f641d8e88473.png)

**Expected Behavior**
Just after both sides are fully funded, we move to Appeled status, and a message is displayed on the left side informing users that Jurors will evaluate the appeal and a decision will be made in x time. After jurors' decision is made the Appeal module is then displayed again allowing another appeal funding round. Check the design.

**Comment by epiqueras** [comment]
We didn't do that because it doesn't work with parallel challenges.

Each challenge has its lifecycle, so you can't show one global appeal status for the whole submission.
