### ISSUE TITLE
Self fund UI

### ISSUE THREAD

**Issue by clesaege** [Proof-Of-Humanity/proof-of-humanity-web#87]
![image](https://user-images.githubusercontent.com/8873352/108539946-854f4800-72d8-11eb-96ec-d9d590cdb39b.png)
"Self fund" should be of the same style as "Crowdfund".
"Self fund" should be selected by default (it will make it look different, not because it is different but because it is selected).

Currently when you click somewhere else, the option unselects. It should stay selected.

**Comment by epiqueras** [comment]
Done
