### ISSUE TITLE
Get an info message for not filling Eth amount when submitting a profile

### ISSUE THREAD

**Issue by PresenceNumerique** [Proof-Of-Humanity/proof-of-humanity-web#9]
**Is your feature request related to a problem?**
Tried to submit a profile without filling the initial contribution field:
I got no warning that this field is required which implies wondering why submitting doesn't work.

**Describe the solution you'd like.**
Just display a warning message that this field is required (like it has been done for other fields).

**Describe alternatives you've considered.**

**Comment by epiqueras** [comment]
It's not a required field.

I fixed the issue that was not letting you submit.
