### ISSUE TITLE
Update the interface for the new UBI contract

### ISSUE THREAD

**Issue by clesaege** [Proof-Of-Humanity/proof-of-humanity-web#90]
![image](https://user-images.githubusercontent.com/8873352/108746070-c000ec80-7533-11eb-8254-218a5e9b11f9.png)

No more UBI accrued (remove the word "accrued") and show the balance updating in real time.
No more claim button.

**Comment by jragosa** [comment]
Can this be closed @clesaege ?

**Comment by jragosa** [comment]
Can this be closed @clesaege ?
