### ISSUE TITLE
Video above 10mb

### ISSUE THREAD

**Issue by federicoast** [Proof-Of-Humanity/proof-of-humanity-web#93]
When you try to upload a video which weighs more than 10mb, you get a "required" warning message. But you should get a message kind of "File size cannot exceed 10mb"

<img width="878" alt="Captura de pantalla 2021-03-10 194139" src="https://user-images.githubusercontent.com/16290963/110707898-b71d4580-81d8-11eb-8190-56537c8bf41e.png">

**Comment by hbarcelos** [comment]
Fixed already.
